In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, classification_report
import xarray as xr
import xgboost as xgb
import optuna

In [4]:
folder = Path(r"D:\INCOIS\Data_Float_Fixed")

files = sorted(folder.glob("*.nc"))

phyto_ds = xr.open_dataset(
    r"D:\INCOIS\PHYTOBLOOM_GOM.nc"
)

In [5]:
r=[]

In [6]:
for file in files:

    date = pd.to_datetime(
        file.name[1:9],
        format="%Y%m%d"
    )

    if date.year <= 2023:
        continue

    ds = xr.open_dataset(file)

    ds = ds.sel(
        lat=slice(11,7),
        lon=slice(78,81)
    )

    chlor = ds["CHLOR_A"].values.ravel()

    bloom = (
        phyto_ds["PHYTOBLOOM"]
        .sel(time=date)
        .values
        .ravel()
    )

    lat_grid, lon_grid = np.meshgrid(
    ds["lat"].values,
    ds["lon"].values,
    indexing="ij"
)

    temp = pd.DataFrame({
    "date": date,
    "LAT": lat_grid.ravel(),
    "LON": lon_grid.ravel(),
    "CHLOR_A": chlor,
    "PHYTOBLOOM": bloom
    })
    
    
    r.append(temp)

In [7]:
df_test = pd.concat(r, ignore_index=True)
print(len(df_test))
df_test

4817664

              date        LAT        LON  CHLOR_A  PHYTOBLOOM
0       2024-01-01  10.979163  78.020836      NaN         NaN
1       2024-01-01  10.979163  78.062500      NaN         NaN
2       2024-01-01  10.979163  78.104172      NaN         NaN
3       2024-01-01  10.979163  78.145836      NaN         NaN
4       2024-01-01  10.979163  78.187500      NaN         NaN
...            ...        ...        ...      ...         ...
4817659 2025-11-30   7.020830  80.812500      NaN         NaN
4817660 2025-11-30   7.020830  80.854172      NaN         NaN
4817661 2025-11-30   7.020830  80.895836      NaN         NaN
4817662 2025-11-30   7.020830  80.937500      NaN         NaN
4817663 2025-11-30   7.020830  80.979172      NaN         NaN

[4817664 rows x 5 columns]

In [8]:
df_test = df_test.dropna()
len(df_test)

273283

In [9]:
df_test["date"] = pd.to_datetime(df_test["date"])

# Month
df_test["month"] = df_test["date"].dt.month

df_test["month_sin"] = np.sin(
    2 * np.pi * df_test["month"] / 12
)

df_test["month_cos"] = np.cos(
    2 * np.pi * df_test["month"] / 12
)

# Day of year
df_test["dayofyear"] = df_test["date"].dt.dayofyear

df_test["day_sin"] = np.sin(
    2 * np.pi * df_test["dayofyear"] / 365
)

df_test["day_cos"] = np.cos(
    2 * np.pi * df_test["dayofyear"] / 365
)

In [10]:
lat_min = df_test["LAT"].min()
lat_max = df_test["LAT"].max()

df_test["LAT_scaled"] = (
    2 *(df_test["LAT"] - lat_min)/(lat_max - lat_min)- 1
)

lon_min = df_test["LON"].min()
lon_max = df_test["LON"].max()

df_test["LON_scaled"] = (
    2 *(df_test["LON"] - lon_min)/(lon_max - lon_min)- 1
)

In [11]:
df_test.to_csv('test_gom(2024-25).csv')

In [12]:
rows = []

In [13]:
for file in files:

    date = pd.to_datetime(
        file.name[1:9],
        format="%Y%m%d"
    )

    if date.year > 2023:
        continue

    ds = xr.open_dataset(file)

    ds = ds.sel(
        lat=slice(11,7),
        lon=slice(78,81)
    )

    chlor = ds["CHLOR_A"].values.ravel()

    bloom = (
        phyto_ds["PHYTOBLOOM"]
        .sel(time=date)
        .values
        .ravel()
    )

    lat_grid, lon_grid = np.meshgrid(
    ds["lat"].values,
    ds["lon"].values,
    indexing="ij"
    )

    temp = pd.DataFrame({
    "date": date,
    "LAT": lat_grid.ravel(),
    "LON": lon_grid.ravel(),
    "CHLOR_A": chlor,
    "PHYTOBLOOM": bloom
    })

    
    rows.append(temp)

In [14]:
df = pd.concat(rows, ignore_index=True)
print(len(df))
df

52856064

               date        LAT        LON  CHLOR_A  PHYTOBLOOM
0        2003-01-01  10.979163  78.020836      NaN         NaN
1        2003-01-01  10.979163  78.062500      NaN         NaN
2        2003-01-01  10.979163  78.104172      NaN         NaN
3        2003-01-01  10.979163  78.145836      NaN         NaN
4        2003-01-01  10.979163  78.187500      NaN         NaN
...             ...        ...        ...      ...         ...
52856059 2023-12-31   7.020830  80.812500      NaN         NaN
52856060 2023-12-31   7.020830  80.854172      NaN         NaN
52856061 2023-12-31   7.020830  80.895836      NaN         NaN
52856062 2023-12-31   7.020830  80.937500      NaN         NaN
52856063 2023-12-31   7.020830  80.979172      NaN         NaN

[52856064 rows x 5 columns]

In [15]:
df = df.dropna()
len(df)

4082861

In [16]:
df["date"] = pd.to_datetime(df["date"])

# Month
df["month"] = df["date"].dt.month

df["month_sin"] = np.sin(
    2 * np.pi * df["month"] / 12
)

df["month_cos"] = np.cos(
    2 * np.pi * df["month"] / 12
)

# Day of year
df["dayofyear"] = df["date"].dt.dayofyear

df["day_sin"] = np.sin(
    2 * np.pi * df["dayofyear"] / 365
)

df["day_cos"] = np.cos(
    2 * np.pi * df["dayofyear"] / 365
)

In [17]:
lat_min = df["LAT"].min()
lat_max = df["LAT"].max()

df["LAT_scaled"] = (
    2 *(df["LAT"] - lat_min)/(lat_max - lat_min)- 1
)

lon_min = df["LON"].min()
lon_max = df["LON"].max()
df["LON_scaled"] = (
    2 *(df["LON"] - lon_min)/(lon_max - lon_min)- 1
)

In [18]:
df.to_csv('training_gom(2003-2023).csv')

In [2]:
train_df = pd.read_csv("training_gom(2003-2023).csv")
test_df = pd.read_csv("test_gom(2024-25).csv")

print(train_df.shape)
print(test_df.shape)

(4082861, 14)
(273283, 14)

In [3]:
FEATURES = [
    "CHLOR_A",
    "day_sin",
    "day_cos",
    "month_sin",
    "month_cos",
    "LAT_scaled",
    "LON_scaled"
]

TARGET = "PHYTOBLOOM"

In [4]:
X_train = train_df[FEATURES]
y_train = train_df[TARGET]

X_test = test_df[FEATURES]
y_test = test_df[TARGET]

In [8]:

import joblib

final_model =  joblib.load('lgb_model_GOM.pkl')

final_model.fit(
    X_train,
    y_train
)

[LightGBM] [Warning] Unknown parameter: weight_mode
[LightGBM] [Warning] Unknown parameter: weight_mode
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.024363 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 928
[LightGBM] [Info] Number of data points in the train set: 4082861, number of used features: 7
[LightGBM] [Info] Start training from score -0.145816
[LightGBM] [Info] Start training from score -3.131013
[LightGBM] [Info] Start training from score -2.385858

LGBMClassifier(colsample_bytree=0.8013089285041655,
               learning_rate=0.02738388850765012, max_depth=12,
               min_child_samples=46, min_split_gain=0.0012963994780004645,
               n_estimators=60, num_class=3, num_leaves=39,
               objective='multiclass', random_state=42,
               reg_alpha=0.06198542335852684, reg_lambda=0.004700171913470125,
               subsample=0.8704588059140501, weight_mode='sqrt_balanced')

In [9]:
y_pred1 = final_model.predict(
    X_train
)
y_pred = final_model.predict(
    X_test
)

[LightGBM] [Warning] Unknown parameter: weight_mode
[LightGBM] [Warning] Unknown parameter: weight_mode

In [10]:
print("TRAIN RESULTS")
print(
    classification_report(
        y_train,
        y_pred1
    )
)

macro_f1 = f1_score(
    y_train,
    y_pred1,
    average="macro"
)

print(
    "Train Macro F1:",
    macro_f1
)
print()
print("TEST RESULTS")
print(
    classification_report(
        y_test,
        y_pred
    )
)

macro_f1 = f1_score(
    y_test,
    y_pred,
    average="macro"
)

print(
    "Test Macro F1:",
    macro_f1
)

TRAIN RESULTS
              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98   3528884
         1.0       0.83      0.61      0.70    178313
         2.0       0.88      0.83      0.85    375664

    accuracy                           0.96   4082861
   macro avg       0.89      0.81      0.85   4082861
weighted avg       0.96      0.96      0.96   4082861

Train Macro F1: 0.8455972920721865

TEST RESULTS
              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98    232342
         1.0       0.69      0.67      0.68     12506
         2.0       0.86      0.76      0.81     28435

    accuracy                           0.95    273283
   macro avg       0.84      0.81      0.82    273283
weighted avg       0.95      0.95      0.95    273283

Test Macro F1: 0.8223642394415424

In [27]:
from xgboost import XGBClassifier

model = XGBClassifier(
    objective="multi:softmax",
    num_class=3,
    random_state=42
)

In [28]:
model.fit(
    X_train,
    y_train
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_class=3, ...)

In [29]:
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

In [30]:
print("TRAIN RESULTS\n")

print(classification_report(y_train, train_pred))


print("Macro F1:",
      f1_score(y_train, train_pred, average='macro'))


print("\n\nTEST RESULTS\n")

print(classification_report(y_test, test_pred))


print("Macro F1:",
      f1_score(y_test, test_pred, average='macro'))

TRAIN RESULTS

              precision    recall  f1-score   support

         0.0       0.98      0.99      0.99   3528884
         1.0       0.82      0.71      0.76    178313
         2.0       0.88      0.87      0.88    375664

    accuracy                           0.97   4082861
   macro avg       0.90      0.86      0.87   4082861
weighted avg       0.97      0.97      0.97   4082861

Macro F1: 0.8743138662093388


TEST RESULTS

              precision    recall  f1-score   support

         0.0       0.98      0.98      0.98    232342
         1.0       0.66      0.72      0.69     12506
         2.0       0.86      0.79      0.82     28435

    accuracy                           0.95    273283
   macro avg       0.83      0.83      0.83    273283
weighted avg       0.95      0.95      0.95    273283

Macro F1: 0.8323818100684545

In [23]:
def objective_multi(trial):
    params = {
        "objective": "multi:softprob",
        "num_class": 3,

        "n_estimators": trial.suggest_int("n_estimators", 30, 300, step=10),
        "max_depth": trial.suggest_int("max_depth", 3, 14),  # narrowed hard around 4
        "learning_rate": trial.suggest_float("learning_rate", 0.10, 0.24, log=True),
        "subsample": trial.suggest_float("subsample", 0.70, 0.85),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.65, 0.85),
        "min_child_weight": trial.suggest_int("min_child_weight", 18, 30),
        "gamma": trial.suggest_float("gamma", 0.05, 0.5, log=True),
        "lambda": trial.suggest_float("lambda", 0.4, 2.5, log=True),
        "alpha": trial.suggest_float("alpha", 1.7, 2.8),
        "grow_policy": trial.suggest_categorical("grow_policy", ["depthwise", "lossguide"]),

        "tree_method": "hist",
        "random_state": 42,
        "n_jobs": -1,
    }


    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    gaps, val_scores = [], []

    for train_idx, val_idx in skf.split(X_train, y_train):
        X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

        model = xgb.XGBClassifier(**params)
        model.fit(X_tr, y_tr, verbose=False)

        train_f1 = f1_score(y_tr, model.predict(X_tr), average="macro")
        val_f1 = f1_score(y_val, model.predict(X_val), average="macro")

        val_scores.append(val_f1)
        gaps.append(train_f1 - val_f1)

    mean_val = np.mean(val_scores)
    mean_gap = np.mean(gaps)

    # Return a tuple: optuna will treat this as two objectives
    return mean_val, mean_gap

In [24]:
study = optuna.create_study(directions=["maximize", "minimize"]) 
study.optimize(objective_multi, n_trials=40, show_progress_bar=True)

[I 2026-07-16 10:42:12,935] A new study created in memory with name: no-name-298b271c-ec31-435a-9502-dcce235e3b00

  0%|          | 0/40 [00:00<?, ?it/s]

[I 2026-07-16 10:49:11,400] Trial 0 finished with values: [0.8803556255351564, 0.00527797937065515] and parameters: {'n_estimators': 150, 'max_depth': 8, 'learning_rate': 0.1977180514202269, 'subsample': 0.7950136458658352, 'colsample_bytree': 0.7589405890422465, 'min_child_weight': 23, 'gamma': 0.3951682011855159, 'lambda': 0.6481280260414632, 'alpha': 1.9284334369843046, 'grow_policy': 'depthwise'}.
[I 2026-07-16 11:06:39,028] Trial 1 finished with values: [0.8926044232521196, 0.017684263254462106] and parameters: {'n_estimators': 200, 'max_depth': 13, 'learning_rate': 0.14652397195818664, 'subsample': 0.7572092538692679, 'colsample_bytree': 0.7690703199670946, 'min_child_weight': 26, 'gamma': 0.13016623870199828, 'lambda': 1.5987038615192182, 'alpha': 2.0277849854472483, 'grow_policy': 'lossguide'}.
[I 2026-07-16 11:13:02,765] Trial 2 finished with values: [0.8852223115289322, 0.009846353639097472] and parameters: {'n_estimators': 120, 'max_depth': 12, 'learning_rate': 0.13594256036681107, 'subsample': 0.8182144017016628, 'colsample_bytree': 0.6657920047201418, 'min_child_weight': 30, 'gamma': 0.09687740931436088, 'lambda': 1.388877277355275, 'alpha': 1.8833453360077217, 'grow_policy': 'depthwise'}.
[I 2026-07-16 11:28:23,043] Trial 3 finished with values: [0.8744377916247954, 0.00274905962939751] and parameters: {'n_estimators': 180, 'max_depth': 7, 'learning_rate': 0.1467313703829761, 'subsample': 0.8295196544886779, 'colsample_bytree': 0.713869298077358, 'min_child_weight': 26, 'gamma': 0.07180240697475329, 'lambda': 0.5207837566795598, 'alpha': 1.7829860859947315, 'grow_policy': 'lossguide'}.
[I 2026-07-16 12:00:42,156] Trial 4 finished with values: [0.8856515664845921, 0.009304149770880298] and parameters: {'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.23406730896218486, 'subsample': 0.8321865215773379, 'colsample_bytree': 0.7015767751690662, 'min_child_weight': 22, 'gamma': 0.12537564781193997, 'lambda': 0.5074110832023121, 'alpha': 2.2769339254441316, 'grow_policy': 'depthwise'}.
[I 2026-07-16 12:38:47,218] Trial 5 finished with values: [0.8968618123950336, 0.02736885106235378] and parameters: {'n_estimators': 290, 'max_depth': 14, 'learning_rate': 0.1712164763348071, 'subsample': 0.835293681430175, 'colsample_bytree': 0.7346216459166288, 'min_child_weight': 18, 'gamma': 0.21544962779249077, 'lambda': 0.8444890028868497, 'alpha': 2.4237648005604306, 'grow_policy': 'depthwise'}.
[I 2026-07-16 12:50:12,626] Trial 6 finished with values: [0.8916615808556345, 0.015715222295226816] and parameters: {'n_estimators': 190, 'max_depth': 13, 'learning_rate': 0.12696370379074978, 'subsample': 0.752570655259925, 'colsample_bytree': 0.8157972372898347, 'min_child_weight': 24, 'gamma': 0.21462653438560222, 'lambda': 1.2639791323749268, 'alpha': 2.0633352686262065, 'grow_policy': 'depthwise'}.
[I 2026-07-16 13:08:30,021] Trial 7 finished with values: [0.8929308306259227, 0.01801790945316071] and parameters: {'n_estimators': 260, 'max_depth': 13, 'learning_rate': 0.11087617721691649, 'subsample': 0.8362341093691102, 'colsample_bytree': 0.7887914604923936, 'min_child_weight': 28, 'gamma': 0.06333489546975088, 'lambda': 0.6934239806517426, 'alpha': 1.8629481684803166, 'grow_policy': 'lossguide'}.
[I 2026-07-16 13:21:14,693] Trial 8 finished with values: [0.8844291663650765, 0.007090717587722483] and parameters: {'n_estimators': 290, 'max_depth': 8, 'learning_rate': 0.15203429918156428, 'subsample': 0.7847020330566012, 'colsample_bytree': 0.8001700673687493, 'min_child_weight': 22, 'gamma': 0.08251857551765868, 'lambda': 1.2489049745002783, 'alpha': 2.0820384390640716, 'grow_policy': 'lossguide'}.
[I 2026-07-16 13:33:27,320] Trial 9 finished with values: [0.8853308447310069, 0.008002490851262345] and parameters: {'n_estimators': 260, 'max_depth': 9, 'learning_rate': 0.1308648700941238, 'subsample': 0.7729170647691209, 'colsample_bytree': 0.7725006602129256, 'min_child_weight': 23, 'gamma': 0.09721144348600333, 'lambda': 0.4517351408016581, 'alpha': 2.7286117900438285, 'grow_policy': 'lossguide'}.
[I 2026-07-16 13:44:37,704] Trial 10 finished with values: [0.8900701877884906, 0.014046906063361852] and parameters: {'n_estimators': 130, 'max_depth': 14, 'learning_rate': 0.11828522810209591, 'subsample': 0.717574103994849, 'colsample_bytree': 0.7776196979009834, 'min_child_weight': 23, 'gamma': 0.155459550787635, 'lambda': 0.9245918602604317, 'alpha': 2.096886551095598, 'grow_policy': 'lossguide'}.
[I 2026-07-16 13:50:24,665] Trial 11 finished with values: [0.8762590500166543, 0.006805519615488809] and parameters: {'n_estimators': 40, 'max_depth': 14, 'learning_rate': 0.10487678634809752, 'subsample': 0.8191780922800408, 'colsample_bytree': 0.7807715875735673, 'min_child_weight': 29, 'gamma': 0.09544132200839614, 'lambda': 1.0029445324708746, 'alpha': 2.0684280650371747, 'grow_policy': 'lossguide'}.
[I 2026-07-16 14:07:06,967] Trial 12 finished with values: [0.8841349376744587, 0.007520696105601399] and parameters: {'n_estimators': 290, 'max_depth': 8, 'learning_rate': 0.18937806171425087, 'subsample': 0.8473420777978178, 'colsample_bytree': 0.653199308405675, 'min_child_weight': 22, 'gamma': 0.3527355530336816, 'lambda': 0.6297807146950776, 'alpha': 2.1117796987692343, 'grow_policy': 'lossguide'}.
[I 2026-07-16 14:10:38,656] Trial 13 finished with values: [0.8693444226942549, 0.0016120169365227976] and parameters: {'n_estimators': 70, 'max_depth': 7, 'learning_rate': 0.22877953468916423, 'subsample': 0.8011744133285843, 'colsample_bytree': 0.6523316076738134, 'min_child_weight': 27, 'gamma': 0.12251052569954211, 'lambda': 0.9833068882450052, 'alpha': 2.7709049598427002, 'grow_policy': 'depthwise'}.
[I 2026-07-16 14:25:04,503] Trial 14 finished with values: [0.8924256337651577, 0.01708920341671958] and parameters: {'n_estimators': 240, 'max_depth': 12, 'learning_rate': 0.16905005061936046, 'subsample': 0.7358716412938062, 'colsample_bytree': 0.7996043665603801, 'min_child_weight': 29, 'gamma': 0.11359875474062667, 'lambda': 2.0401735584691476, 'alpha': 2.6240759694964373, 'grow_policy': 'depthwise'}.
[I 2026-07-16 14:34:59,966] Trial 15 finished with values: [0.8930193425944747, 0.022782528596015993] and parameters: {'n_estimators': 160, 'max_depth': 14, 'learning_rate': 0.1808797269481915, 'subsample': 0.7318688471715499, 'colsample_bytree': 0.696950414583356, 'min_child_weight': 19, 'gamma': 0.06769424859427167, 'lambda': 0.6867702937993955, 'alpha': 1.8652088432803087, 'grow_policy': 'depthwise'}.
[I 2026-07-16 14:46:00,025] Trial 16 finished with values: [0.8924998109188469, 0.021477461903843344] and parameters: {'n_estimators': 120, 'max_depth': 14, 'learning_rate': 0.2326564263290191, 'subsample': 0.7347526113199705, 'colsample_bytree': 0.7077793600824085, 'min_child_weight': 19, 'gamma': 0.06353520568147711, 'lambda': 2.2373754545668043, 'alpha': 1.9297800395480467, 'grow_policy': 'lossguide'}.
[I 2026-07-16 14:59:54,952] Trial 17 finished with values: [0.8812562285200162, 0.005493076297432009] and parameters: {'n_estimators': 260, 'max_depth': 8, 'learning_rate': 0.11899721571137997, 'subsample': 0.7356007456947159, 'colsample_bytree': 0.811791900499515, 'min_child_weight': 19, 'gamma': 0.31990975787406545, 'lambda': 0.8026240463668923, 'alpha': 2.024344412604918, 'grow_policy': 'lossguide'}.
[I 2026-07-16 15:07:47,202] Trial 18 finished with values: [0.88813101632645, 0.011066902434917947] and parameters: {'n_estimators': 180, 'max_depth': 10, 'learning_rate': 0.21267981651398254, 'subsample': 0.809265479926281, 'colsample_bytree': 0.8168390466988226, 'min_child_weight': 29, 'gamma': 0.3061099422160932, 'lambda': 1.9116461339641717, 'alpha': 1.9168256988536494, 'grow_policy': 'depthwise'}.
[I 2026-07-16 15:11:55,098] Trial 19 finished with values: [0.8427341922167135, 0.0001801702037452113] and parameters: {'n_estimators': 130, 'max_depth': 3, 'learning_rate': 0.13043703802888143, 'subsample': 0.7145726876205474, 'colsample_bytree': 0.6683774694332383, 'min_child_weight': 20, 'gamma': 0.33960977782654655, 'lambda': 0.4067264179072404, 'alpha': 2.495591111639058, 'grow_policy': 'depthwise'}.
[I 2026-07-16 15:16:45,790] Trial 20 finished with values: [0.8418965082804897, 0.0001714995674780173] and parameters: {'n_estimators': 140, 'max_depth': 3, 'learning_rate': 0.10881987858257748, 'subsample': 0.8446526339839784, 'colsample_bytree': 0.8003642023896022, 'min_child_weight': 20, 'gamma': 0.2573469603906708, 'lambda': 2.302483337281246, 'alpha': 2.462096139775924, 'grow_policy': 'depthwise'}.
[I 2026-07-16 15:30:27,457] Trial 21 finished with values: [0.8920451825768083, 0.0185731143338431] and parameters: {'n_estimators': 270, 'max_depth': 13, 'learning_rate': 0.1424086669654489, 'subsample': 0.7423161408951902, 'colsample_bytree': 0.714143113475938, 'min_child_weight': 29, 'gamma': 0.12235810033239836, 'lambda': 0.6031779136593705, 'alpha': 2.4129852875021003, 'grow_policy': 'depthwise'}.
[I 2026-07-16 15:34:47,455] Trial 22 finished with values: [0.8772174135433914, 0.00399337168660312] and parameters: {'n_estimators': 110, 'max_depth': 8, 'learning_rate': 0.19317846984777126, 'subsample': 0.7078700075271441, 'colsample_bytree': 0.8351037013049307, 'min_child_weight': 20, 'gamma': 0.31812315918749895, 'lambda': 0.5727478095286361, 'alpha': 2.2415399457988316, 'grow_policy': 'lossguide'}.
[I 2026-07-16 15:40:53,692] Trial 23 finished with values: [0.8827697096803492, 0.00789061159837665] and parameters: {'n_estimators': 110, 'max_depth': 11, 'learning_rate': 0.15071753198488053, 'subsample': 0.7068583871632161, 'colsample_bytree': 0.7045127566187288, 'min_child_weight': 28, 'gamma': 0.058207196168681634, 'lambda': 0.4440851487987969, 'alpha': 2.0441548849571953, 'grow_policy': 'lossguide'}.
[I 2026-07-16 15:45:47,720] Trial 24 finished with values: [0.8880164104560364, 0.01254150952454507] and parameters: {'n_estimators': 80, 'max_depth': 13, 'learning_rate': 0.2180571835018887, 'subsample': 0.7270918663265975, 'colsample_bytree': 0.7182232565507134, 'min_child_weight': 28, 'gamma': 0.19967761599862102, 'lambda': 1.2687723713802126, 'alpha': 1.8937102995181272, 'grow_policy': 'depthwise'}.
[I 2026-07-16 15:58:26,813] Trial 25 finished with values: [0.8924805398099467, 0.01718901071065442] and parameters: {'n_estimators': 210, 'max_depth': 12, 'learning_rate': 0.19880572234352822, 'subsample': 0.8004791801462782, 'colsample_bytree': 0.749372876319055, 'min_child_weight': 24, 'gamma': 0.31535516369967903, 'lambda': 1.321559869960061, 'alpha': 2.3555037034596666, 'grow_policy': 'lossguide'}.
[I 2026-07-16 16:04:50,765] Trial 26 finished with values: [0.8872016192599397, 0.011515529844814654] and parameters: {'n_estimators': 90, 'max_depth': 12, 'learning_rate': 0.19587292342604923, 'subsample': 0.812345302108754, 'colsample_bytree': 0.8185447726862758, 'min_child_weight': 26, 'gamma': 0.052856387980140515, 'lambda': 0.7693008407184154, 'alpha': 1.9987835896453716, 'grow_policy': 'depthwise'}.
[I 2026-07-16 16:19:02,407] Trial 27 finished with values: [0.8900234518520118, 0.015012596234852803] and parameters: {'n_estimators': 130, 'max_depth': 14, 'learning_rate': 0.11175592476657491, 'subsample': 0.8284537929647044, 'colsample_bytree': 0.828299965205049, 'min_child_weight': 24, 'gamma': 0.15271645333266126, 'lambda': 0.746655800826616, 'alpha': 1.7568888167312067, 'grow_policy': 'lossguide'}.
[I 2026-07-16 16:26:43,563] Trial 28 finished with values: [0.866696130059257, 0.0012498545420529972] and parameters: {'n_estimators': 170, 'max_depth': 6, 'learning_rate': 0.10330947896962867, 'subsample': 0.7430981258833605, 'colsample_bytree': 0.7785002356511442, 'min_child_weight': 22, 'gamma': 0.09993962530578573, 'lambda': 1.255860915560861, 'alpha': 2.3264218107351233, 'grow_policy': 'depthwise'}.
[I 2026-07-16 16:32:44,738] Trial 29 finished with values: [0.8756109221939955, 0.003330927220142743] and parameters: {'n_estimators': 130, 'max_depth': 7, 'learning_rate': 0.218685262512239, 'subsample': 0.8187147359631954, 'colsample_bytree': 0.8119397552313183, 'min_child_weight': 30, 'gamma': 0.139542716149092, 'lambda': 1.4279060940652226, 'alpha': 2.3047310649118895, 'grow_policy': 'depthwise'}.
[I 2026-07-16 16:47:24,709] Trial 30 finished with values: [0.890896836250992, 0.014067942832397007] and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.1644826334694413, 'subsample': 0.7829274198095508, 'colsample_bytree': 0.7345641657211657, 'min_child_weight': 25, 'gamma': 0.1371714879084116, 'lambda': 0.787315246263394, 'alpha': 1.9975656693650108, 'grow_policy': 'depthwise'}.
[I 2026-07-16 16:56:04,414] Trial 31 finished with values: [0.8686024871234466, 0.0015716949785781642] and parameters: {'n_estimators': 200, 'max_depth': 6, 'learning_rate': 0.11734732118533125, 'subsample': 0.704317699014678, 'colsample_bytree': 0.6875813142969456, 'min_child_weight': 19, 'gamma': 0.40398824585318077, 'lambda': 1.2234731279501623, 'alpha': 1.70764330328268, 'grow_policy': 'lossguide'}.
[I 2026-07-16 17:06:06,697] Trial 32 finished with values: [0.8630472438043497, 0.0009462896024520883] and parameters: {'n_estimators': 280, 'max_depth': 4, 'learning_rate': 0.147854209222659, 'subsample': 0.8293200114499562, 'colsample_bytree': 0.6851709631211007, 'min_child_weight': 23, 'gamma': 0.23902935634816913, 'lambda': 1.177402669450511, 'alpha': 1.8742270350846404, 'grow_policy': 'depthwise'}.
[I 2026-07-16 17:19:33,424] Trial 33 finished with values: [0.887667313566072, 0.010551345006193013] and parameters: {'n_estimators': 280, 'max_depth': 9, 'learning_rate': 0.16297917031428244, 'subsample': 0.7402477700867727, 'colsample_bytree': 0.7718624725022797, 'min_child_weight': 22, 'gamma': 0.09794244086782061, 'lambda': 1.2077638769946637, 'alpha': 1.9664718123031282, 'grow_policy': 'lossguide'}.
[I 2026-07-16 17:27:49,236] Trial 34 finished with values: [0.8884910683462802, 0.013816784198449205] and parameters: {'n_estimators': 140, 'max_depth': 14, 'learning_rate': 0.10822334736383891, 'subsample': 0.8320697564996805, 'colsample_bytree': 0.6776377120219241, 'min_child_weight': 24, 'gamma': 0.056052399444730956, 'lambda': 1.9612223087471203, 'alpha': 2.0829005506870635, 'grow_policy': 'depthwise'}.
[I 2026-07-16 17:42:08,429] Trial 35 finished with values: [0.8955986983389537, 0.024592369227778986] and parameters: {'n_estimators': 270, 'max_depth': 12, 'learning_rate': 0.21903424160568466, 'subsample': 0.7856803741688856, 'colsample_bytree': 0.7298920328102295, 'min_child_weight': 25, 'gamma': 0.06644594165590427, 'lambda': 0.7500829524871306, 'alpha': 2.121421069718481, 'grow_policy': 'depthwise'}.
[I 2026-07-16 17:52:35,338] Trial 36 finished with values: [0.8829607562126892, 0.007254576058422479] and parameters: {'n_estimators': 180, 'max_depth': 10, 'learning_rate': 0.11264448076889105, 'subsample': 0.8178513584359387, 'colsample_bytree': 0.7038770627856002, 'min_child_weight': 19, 'gamma': 0.23698612661324817, 'lambda': 0.6628280784250369, 'alpha': 2.3363309645396884, 'grow_policy': 'lossguide'}.
[I 2026-07-16 17:57:16,552] Trial 37 finished with values: [0.8569370498012079, 0.0007295941452670984] and parameters: {'n_estimators': 110, 'max_depth': 4, 'learning_rate': 0.1865120956503364, 'subsample': 0.8060715614500655, 'colsample_bytree': 0.8035129660300107, 'min_child_weight': 18, 'gamma': 0.10737994378520181, 'lambda': 0.8665748399892303, 'alpha': 2.2691618959651247, 'grow_policy': 'lossguide'}.
[I 2026-07-16 18:24:58,096] Trial 38 finished with values: [0.857287847032398, 0.000563712380455983] and parameters: {'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.14956283331096298, 'subsample': 0.7894346487836463, 'colsample_bytree': 0.740607560876696, 'min_child_weight': 27, 'gamma': 0.06886942130758135, 'lambda': 0.4096949718084361, 'alpha': 1.738231244056319, 'grow_policy': 'lossguide'}.
[I 2026-07-16 18:37:53,611] Trial 39 finished with values: [0.8906686624068281, 0.014888322074296977] and parameters: {'n_estimators': 180, 'max_depth': 11, 'learning_rate': 0.2346562487103268, 'subsample': 0.723370538180877, 'colsample_bytree': 0.7182880772013748, 'min_child_weight': 30, 'gamma': 0.16748659681728734, 'lambda': 0.40364127768027114, 'alpha': 2.357578165442914, 'grow_policy': 'depthwise'}.

In [45]:
best_trials = study.best_trials
i=0

for t in best_trials:
    print(f"{i} val_f1={t.values[0]:.4f}, gap={t.values[1]:.4f}, params={t.params}")
    i+=1

0 val_f1=0.8804, gap=0.0053, params={'n_estimators': 150, 'max_depth': 8, 'learning_rate': 0.1977180514202269, 'subsample': 0.7950136458658352, 'colsample_bytree': 0.7589405890422465, 'min_child_weight': 23, 'gamma': 0.3951682011855159, 'lambda': 0.6481280260414632, 'alpha': 1.9284334369843046, 'grow_policy': 'depthwise'}
1 val_f1=0.8926, gap=0.0177, params={'n_estimators': 200, 'max_depth': 13, 'learning_rate': 0.14652397195818664, 'subsample': 0.7572092538692679, 'colsample_bytree': 0.7690703199670946, 'min_child_weight': 26, 'gamma': 0.13016623870199828, 'lambda': 1.5987038615192182, 'alpha': 2.0277849854472483, 'grow_policy': 'lossguide'}
2 val_f1=0.8744, gap=0.0027, params={'n_estimators': 180, 'max_depth': 7, 'learning_rate': 0.1467313703829761, 'subsample': 0.8295196544886779, 'colsample_bytree': 0.713869298077358, 'min_child_weight': 26, 'gamma': 0.07180240697475329, 'lambda': 0.5207837566795598, 'alpha': 1.7829860859947315, 'grow_policy': 'lossguide'}
3 val_f1=0.8857, gap=0.0093, params={'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.23406730896218486, 'subsample': 0.8321865215773379, 'colsample_bytree': 0.7015767751690662, 'min_child_weight': 22, 'gamma': 0.12537564781193997, 'lambda': 0.5074110832023121, 'alpha': 2.2769339254441316, 'grow_policy': 'depthwise'}
4 val_f1=0.8969, gap=0.0274, params={'n_estimators': 290, 'max_depth': 14, 'learning_rate': 0.1712164763348071, 'subsample': 0.835293681430175, 'colsample_bytree': 0.7346216459166288, 'min_child_weight': 18, 'gamma': 0.21544962779249077, 'lambda': 0.8444890028868497, 'alpha': 2.4237648005604306, 'grow_policy': 'depthwise'}
5 val_f1=0.8917, gap=0.0157, params={'n_estimators': 190, 'max_depth': 13, 'learning_rate': 0.12696370379074978, 'subsample': 0.752570655259925, 'colsample_bytree': 0.8157972372898347, 'min_child_weight': 24, 'gamma': 0.21462653438560222, 'lambda': 1.2639791323749268, 'alpha': 2.0633352686262065, 'grow_policy': 'depthwise'}
6 val_f1=0.8929, gap=0.0180, params={'n_estimators': 260, 'max_depth': 13, 'learning_rate': 0.11087617721691649, 'subsample': 0.8362341093691102, 'colsample_bytree': 0.7887914604923936, 'min_child_weight': 28, 'gamma': 0.06333489546975088, 'lambda': 0.6934239806517426, 'alpha': 1.8629481684803166, 'grow_policy': 'lossguide'}
7 val_f1=0.8844, gap=0.0071, params={'n_estimators': 290, 'max_depth': 8, 'learning_rate': 0.15203429918156428, 'subsample': 0.7847020330566012, 'colsample_bytree': 0.8001700673687493, 'min_child_weight': 22, 'gamma': 0.08251857551765868, 'lambda': 1.2489049745002783, 'alpha': 2.0820384390640716, 'grow_policy': 'lossguide'}
8 val_f1=0.8853, gap=0.0080, params={'n_estimators': 260, 'max_depth': 9, 'learning_rate': 0.1308648700941238, 'subsample': 0.7729170647691209, 'colsample_bytree': 0.7725006602129256, 'min_child_weight': 23, 'gamma': 0.09721144348600333, 'lambda': 0.4517351408016581, 'alpha': 2.7286117900438285, 'grow_policy': 'lossguide'}
9 val_f1=0.8901, gap=0.0140, params={'n_estimators': 130, 'max_depth': 14, 'learning_rate': 0.11828522810209591, 'subsample': 0.717574103994849, 'colsample_bytree': 0.7776196979009834, 'min_child_weight': 23, 'gamma': 0.155459550787635, 'lambda': 0.9245918602604317, 'alpha': 2.096886551095598, 'grow_policy': 'lossguide'}
10 val_f1=0.8693, gap=0.0016, params={'n_estimators': 70, 'max_depth': 7, 'learning_rate': 0.22877953468916423, 'subsample': 0.8011744133285843, 'colsample_bytree': 0.6523316076738134, 'min_child_weight': 27, 'gamma': 0.12251052569954211, 'lambda': 0.9833068882450052, 'alpha': 2.7709049598427002, 'grow_policy': 'depthwise'}
11 val_f1=0.8924, gap=0.0171, params={'n_estimators': 240, 'max_depth': 12, 'learning_rate': 0.16905005061936046, 'subsample': 0.7358716412938062, 'colsample_bytree': 0.7996043665603801, 'min_child_weight': 29, 'gamma': 0.11359875474062667, 'lambda': 2.0401735584691476, 'alpha': 2.6240759694964373, 'grow_policy': 'depthwise'}
12 val_f1=0.8930, gap=0.0228, params={'n_estimators': 160, 'max_depth': 14, 'learning_rate': 0.1808797269481915, 'subsample': 0.7318688471715499, 'colsample_bytree': 0.696950414583356, 'min_child_weight': 19, 'gamma': 0.06769424859427167, 'lambda': 0.6867702937993955, 'alpha': 1.8652088432803087, 'grow_policy': 'depthwise'}
13 val_f1=0.8813, gap=0.0055, params={'n_estimators': 260, 'max_depth': 8, 'learning_rate': 0.11899721571137997, 'subsample': 0.7356007456947159, 'colsample_bytree': 0.811791900499515, 'min_child_weight': 19, 'gamma': 0.31990975787406545, 'lambda': 0.8026240463668923, 'alpha': 2.024344412604918, 'grow_policy': 'lossguide'}
14 val_f1=0.8881, gap=0.0111, params={'n_estimators': 180, 'max_depth': 10, 'learning_rate': 0.21267981651398254, 'subsample': 0.809265479926281, 'colsample_bytree': 0.8168390466988226, 'min_child_weight': 29, 'gamma': 0.3061099422160932, 'lambda': 1.9116461339641717, 'alpha': 1.9168256988536494, 'grow_policy': 'depthwise'}
15 val_f1=0.8427, gap=0.0002, params={'n_estimators': 130, 'max_depth': 3, 'learning_rate': 0.13043703802888143, 'subsample': 0.7145726876205474, 'colsample_bytree': 0.6683774694332383, 'min_child_weight': 20, 'gamma': 0.33960977782654655, 'lambda': 0.4067264179072404, 'alpha': 2.495591111639058, 'grow_policy': 'depthwise'}
16 val_f1=0.8419, gap=0.0002, params={'n_estimators': 140, 'max_depth': 3, 'learning_rate': 0.10881987858257748, 'subsample': 0.8446526339839784, 'colsample_bytree': 0.8003642023896022, 'min_child_weight': 20, 'gamma': 0.2573469603906708, 'lambda': 2.302483337281246, 'alpha': 2.462096139775924, 'grow_policy': 'depthwise'}
17 val_f1=0.8772, gap=0.0040, params={'n_estimators': 110, 'max_depth': 8, 'learning_rate': 0.19317846984777126, 'subsample': 0.7078700075271441, 'colsample_bytree': 0.8351037013049307, 'min_child_weight': 20, 'gamma': 0.31812315918749895, 'lambda': 0.5727478095286361, 'alpha': 2.2415399457988316, 'grow_policy': 'lossguide'}
18 val_f1=0.8925, gap=0.0172, params={'n_estimators': 210, 'max_depth': 12, 'learning_rate': 0.19880572234352822, 'subsample': 0.8004791801462782, 'colsample_bytree': 0.749372876319055, 'min_child_weight': 24, 'gamma': 0.31535516369967903, 'lambda': 1.321559869960061, 'alpha': 2.3555037034596666, 'grow_policy': 'lossguide'}
19 val_f1=0.8667, gap=0.0012, params={'n_estimators': 170, 'max_depth': 6, 'learning_rate': 0.10330947896962867, 'subsample': 0.7430981258833605, 'colsample_bytree': 0.7785002356511442, 'min_child_weight': 22, 'gamma': 0.09993962530578573, 'lambda': 1.255860915560861, 'alpha': 2.3264218107351233, 'grow_policy': 'depthwise'}
20 val_f1=0.8756, gap=0.0033, params={'n_estimators': 130, 'max_depth': 7, 'learning_rate': 0.218685262512239, 'subsample': 0.8187147359631954, 'colsample_bytree': 0.8119397552313183, 'min_child_weight': 30, 'gamma': 0.139542716149092, 'lambda': 1.4279060940652226, 'alpha': 2.3047310649118895, 'grow_policy': 'depthwise'}
21 val_f1=0.8909, gap=0.0141, params={'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.1644826334694413, 'subsample': 0.7829274198095508, 'colsample_bytree': 0.7345641657211657, 'min_child_weight': 25, 'gamma': 0.1371714879084116, 'lambda': 0.787315246263394, 'alpha': 1.9975656693650108, 'grow_policy': 'depthwise'}
22 val_f1=0.8686, gap=0.0016, params={'n_estimators': 200, 'max_depth': 6, 'learning_rate': 0.11734732118533125, 'subsample': 0.704317699014678, 'colsample_bytree': 0.6875813142969456, 'min_child_weight': 19, 'gamma': 0.40398824585318077, 'lambda': 1.2234731279501623, 'alpha': 1.70764330328268, 'grow_policy': 'lossguide'}
23 val_f1=0.8630, gap=0.0009, params={'n_estimators': 280, 'max_depth': 4, 'learning_rate': 0.147854209222659, 'subsample': 0.8293200114499562, 'colsample_bytree': 0.6851709631211007, 'min_child_weight': 23, 'gamma': 0.23902935634816913, 'lambda': 1.177402669450511, 'alpha': 1.8742270350846404, 'grow_policy': 'depthwise'}
24 val_f1=0.8877, gap=0.0106, params={'n_estimators': 280, 'max_depth': 9, 'learning_rate': 0.16297917031428244, 'subsample': 0.7402477700867727, 'colsample_bytree': 0.7718624725022797, 'min_child_weight': 22, 'gamma': 0.09794244086782061, 'lambda': 1.2077638769946637, 'alpha': 1.9664718123031282, 'grow_policy': 'lossguide'}
25 val_f1=0.8885, gap=0.0138, params={'n_estimators': 140, 'max_depth': 14, 'learning_rate': 0.10822334736383891, 'subsample': 0.8320697564996805, 'colsample_bytree': 0.6776377120219241, 'min_child_weight': 24, 'gamma': 0.056052399444730956, 'lambda': 1.9612223087471203, 'alpha': 2.0829005506870635, 'grow_policy': 'depthwise'}
26 val_f1=0.8956, gap=0.0246, params={'n_estimators': 270, 'max_depth': 12, 'learning_rate': 0.21903424160568466, 'subsample': 0.7856803741688856, 'colsample_bytree': 0.7298920328102295, 'min_child_weight': 25, 'gamma': 0.06644594165590427, 'lambda': 0.7500829524871306, 'alpha': 2.121421069718481, 'grow_policy': 'depthwise'}
27 val_f1=0.8573, gap=0.0006, params={'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.14956283331096298, 'subsample': 0.7894346487836463, 'colsample_bytree': 0.740607560876696, 'min_child_weight': 27, 'gamma': 0.06886942130758135, 'lambda': 0.4096949718084361, 'alpha': 1.738231244056319, 'grow_policy': 'lossguide'}

In [9]:
def objective_multi(trial):
    # params = {
    #     "objective": "multi:softprob",
    #     "num_class": 3,

    #     "n_estimators": trial.suggest_int("n_estimators", 20, 90, step=5),
    #     "max_depth": trial.suggest_int("max_depth", 4, 9),
    #     "learning_rate": trial.suggest_float("learning_rate", 0.08, 0.25, log=True),
    #     "subsample": trial.suggest_float("subsample", 0.65, 0.85),
    #     "colsample_bytree": trial.suggest_float("colsample_bytree", 0.65, 0.88),
    #     "min_child_weight": trial.suggest_int("min_child_weight", 15, 30),
    #     "gamma": trial.suggest_float("gamma", 0.02, 1.0, log=True),
    #     "lambda": trial.suggest_float("lambda", 0.3, 5.0, log=True),
    #     "alpha": trial.suggest_float("alpha", 1.6, 2.8),
    #     "grow_policy": trial.suggest_categorical("grow_policy", ["depthwise", "lossguide"]),

    #     "tree_method": "hist",
    #     "random_state": 42,
    #     "n_jobs": -1,
    # }
    params = {
        "objective": "multi:softprob",
        "num_class": 3,
        "n_estimators": trial.suggest_int("n_estimators", 40, 180, step=10),
        "max_depth": trial.suggest_int("max_depth", 5, 9),
        "learning_rate": trial.suggest_float("learning_rate", 0.10, 0.21, log=True),
        "subsample": trial.suggest_float("subsample", 0.70, 0.82),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.65, 0.80),
        "min_child_weight": trial.suggest_int("min_child_weight", 18, 30),
        "gamma": trial.suggest_float("gamma", 0.08, 0.25, log=True),
        "lambda": trial.suggest_float("lambda", 0.4, 2.3, log=True),
        "alpha": trial.suggest_float("alpha", 1.7, 2.4),
        "grow_policy": trial.suggest_categorical("grow_policy", ["depthwise", "lossguide"]),
        "tree_method": "hist",
        "random_state": 42,
        "n_jobs": -1,
    }


    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    gaps, val_scores = [], []

    for train_idx, val_idx in skf.split(X_train, y_train):
        X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

        model = xgb.XGBClassifier(**params)
        model.fit(X_tr, y_tr, verbose=False)

        train_f1 = f1_score(y_tr, model.predict(X_tr), average="macro")
        val_f1 = f1_score(y_val, model.predict(X_val), average="macro")

        val_scores.append(val_f1)
        gaps.append(train_f1 - val_f1)

    mean_val = np.mean(val_scores)
    mean_gap = np.mean(gaps)

    # Return a tuple: optuna will treat this as two objectives
    return mean_val, mean_gap

In [10]:
study = optuna.create_study(directions=["maximize", "minimize"]) 
study.optimize(objective_multi, n_trials=60, show_progress_bar=True)

[I 2026-07-20 11:19:45,774] A new study created in memory with name: no-name-a5799d9c-8d68-4228-abd7-d9dc45284fff

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-07-20 11:24:41,560] Trial 0 finished with values: [0.8725807583855714, 0.0024926626362008707] and parameters: {'n_estimators': 120, 'max_depth': 7, 'learning_rate': 0.16516724609566746, 'subsample': 0.7907493768205527, 'colsample_bytree': 0.7184858951766596, 'min_child_weight': 18, 'gamma': 0.08561689041099817, 'lambda': 1.2794555368058267, 'alpha': 1.7911104661273747, 'grow_policy': 'lossguide'}.
[I 2026-07-20 11:32:09,668] Trial 1 finished with values: [0.8778419213122289, 0.00411847360690174] and parameters: {'n_estimators': 160, 'max_depth': 8, 'learning_rate': 0.14044812840025747, 'subsample': 0.7922564975932839, 'colsample_bytree': 0.7909041685848435, 'min_child_weight': 25, 'gamma': 0.23288975582432148, 'lambda': 0.6348280940525617, 'alpha': 1.8473957052567, 'grow_policy': 'depthwise'}.
[I 2026-07-20 11:39:38,185] Trial 2 finished with values: [0.8773076527002225, 0.004308052145651953] and parameters: {'n_estimators': 150, 'max_depth': 9, 'learning_rate': 0.11181698184920193, 'subsample': 0.7372658395450079, 'colsample_bytree': 0.6505629241841661, 'min_child_weight': 28, 'gamma': 0.1548274450629712, 'lambda': 1.0087772354559612, 'alpha': 2.387414212090693, 'grow_policy': 'depthwise'}.
[I 2026-07-20 11:41:40,264] Trial 3 finished with values: [0.8562229683162339, 0.0005526379340792253] and parameters: {'n_estimators': 40, 'max_depth': 6, 'learning_rate': 0.16298778751056167, 'subsample': 0.7150814517163704, 'colsample_bytree': 0.7208761058553819, 'min_child_weight': 27, 'gamma': 0.19174397380072883, 'lambda': 0.6613590409165381, 'alpha': 2.351157512936108, 'grow_policy': 'lossguide'}.
[I 2026-07-20 11:49:16,261] Trial 4 finished with values: [0.865135181172873, 0.0010764664953936132] and parameters: {'n_estimators': 180, 'max_depth': 5, 'learning_rate': 0.15536859475993905, 'subsample': 0.7037615151398394, 'colsample_bytree': 0.6797861959236203, 'min_child_weight': 30, 'gamma': 0.2410429639101309, 'lambda': 1.9215735885968859, 'alpha': 2.1751975697584385, 'grow_policy': 'depthwise'}.
[I 2026-07-20 11:55:16,697] Trial 5 finished with values: [0.8705019378334958, 0.0017561248648331196] and parameters: {'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.1884524315979021, 'subsample': 0.7196957569859089, 'colsample_bytree': 0.7061000280257759, 'min_child_weight': 18, 'gamma': 0.11307327540956218, 'lambda': 1.3518861928866692, 'alpha': 2.2678694533608614, 'grow_policy': 'depthwise'}.
[I 2026-07-20 11:59:04,150] Trial 6 finished with values: [0.8776224417698751, 0.004398254114954448] and parameters: {'n_estimators': 90, 'max_depth': 9, 'learning_rate': 0.17402194339046403, 'subsample': 0.8002112227992464, 'colsample_bytree': 0.7780845329724659, 'min_child_weight': 28, 'gamma': 0.14679444189485819, 'lambda': 0.5008494903900628, 'alpha': 2.3244311859145625, 'grow_policy': 'depthwise'}.
[I 2026-07-20 12:06:15,325] Trial 7 finished with values: [0.8655054564074541, 0.0011781585082229595] and parameters: {'n_estimators': 180, 'max_depth': 5, 'learning_rate': 0.16136650685432363, 'subsample': 0.7065261644770642, 'colsample_bytree': 0.6669673741519349, 'min_child_weight': 25, 'gamma': 0.10697132660400346, 'lambda': 0.8965429394095551, 'alpha': 2.153661118845485, 'grow_policy': 'lossguide'}.
[I 2026-07-20 12:13:00,251] Trial 8 finished with values: [0.8719944637304808, 0.002385966104555415] and parameters: {'n_estimators': 150, 'max_depth': 7, 'learning_rate': 0.13908143791128888, 'subsample': 0.7260821886050631, 'colsample_bytree': 0.6877265407510897, 'min_child_weight': 21, 'gamma': 0.18111713722875164, 'lambda': 1.2974526467307892, 'alpha': 2.3477387344921796, 'grow_policy': 'lossguide'}.
[I 2026-07-20 12:17:21,791] Trial 9 finished with values: [0.8717755415578583, 0.003132661305203577] and parameters: {'n_estimators': 80, 'max_depth': 9, 'learning_rate': 0.11859436857298727, 'subsample': 0.7685655100548063, 'colsample_bytree': 0.679502762564916, 'min_child_weight': 18, 'gamma': 0.18114602966306315, 'lambda': 1.2076236215908807, 'alpha': 2.0279340882355994, 'grow_policy': 'lossguide'}.
[I 2026-07-20 12:22:54,593] Trial 10 finished with values: [0.8723298177863109, 0.002320695603697742] and parameters: {'n_estimators': 130, 'max_depth': 7, 'learning_rate': 0.149916803987659, 'subsample': 0.819422853145077, 'colsample_bytree': 0.7466049085093802, 'min_child_weight': 21, 'gamma': 0.2253288689297977, 'lambda': 2.25275966065407, 'alpha': 2.3292859872578546, 'grow_policy': 'lossguide'}.
[I 2026-07-20 12:36:57,339] Trial 11 finished with values: [0.8761825059860617, 0.003812106164806184] and parameters: {'n_estimators': 120, 'max_depth': 8, 'learning_rate': 0.15836051068953624, 'subsample': 0.8110502423548335, 'colsample_bytree': 0.7237527786962634, 'min_child_weight': 23, 'gamma': 0.13450300657746567, 'lambda': 1.1212941155002818, 'alpha': 1.745060498748975, 'grow_policy': 'depthwise'}.
[I 2026-07-20 12:40:14,776] Trial 12 finished with values: [0.8685006199496087, 0.0020062742891151066] and parameters: {'n_estimators': 70, 'max_depth': 8, 'learning_rate': 0.14328562403523107, 'subsample': 0.7811448803376148, 'colsample_bytree': 0.7004433208842767, 'min_child_weight': 29, 'gamma': 0.08401986268694984, 'lambda': 1.3157481249740854, 'alpha': 1.9622478673242476, 'grow_policy': 'lossguide'}.
[I 2026-07-20 12:47:36,881] Trial 13 finished with values: [0.8674458097919906, 0.0013464903473165979] and parameters: {'n_estimators': 180, 'max_depth': 6, 'learning_rate': 0.11571619022374996, 'subsample': 0.7659765727395559, 'colsample_bytree': 0.6915443995003668, 'min_child_weight': 24, 'gamma': 0.13471768015207275, 'lambda': 0.8268564102915608, 'alpha': 1.9796393282034779, 'grow_policy': 'lossguide'}.
[I 2026-07-20 12:49:34,014] Trial 14 finished with values: [0.8441389863666995, 0.0004243682879976118] and parameters: {'n_estimators': 50, 'max_depth': 5, 'learning_rate': 0.10014346366622988, 'subsample': 0.7897893894769933, 'colsample_bytree': 0.7218445683052719, 'min_child_weight': 24, 'gamma': 0.08948481326701745, 'lambda': 1.2722224366790063, 'alpha': 2.2699848589656906, 'grow_policy': 'depthwise'}.
[I 2026-07-20 12:52:38,882] Trial 15 finished with values: [0.8611244933791309, 0.0010134194199688195] and parameters: {'n_estimators': 80, 'max_depth': 6, 'learning_rate': 0.11988613501893136, 'subsample': 0.7291282674851081, 'colsample_bytree': 0.7655780577633524, 'min_child_weight': 24, 'gamma': 0.2109606232970809, 'lambda': 0.44629326337651937, 'alpha': 1.8438905185146681, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:00:16,240] Trial 16 finished with values: [0.8722564345901052, 0.0022716261237014424] and parameters: {'n_estimators': 180, 'max_depth': 7, 'learning_rate': 0.10637642952538812, 'subsample': 0.7321080383419165, 'colsample_bytree': 0.7452036441124257, 'min_child_weight': 23, 'gamma': 0.1678863984381845, 'lambda': 1.0591063715214335, 'alpha': 2.1445819045238403, 'grow_policy': 'lossguide'}.
[I 2026-07-20 13:05:26,410] Trial 17 finished with values: [0.8667282727217064, 0.0013971719952161176] and parameters: {'n_estimators': 170, 'max_depth': 5, 'learning_rate': 0.17930494382790768, 'subsample': 0.7690490156526447, 'colsample_bytree': 0.7853851214709331, 'min_child_weight': 18, 'gamma': 0.08156662773321427, 'lambda': 2.161917172420368, 'alpha': 2.2993143874418753, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:07:31,489] Trial 18 finished with values: [0.8623447497968295, 0.001332879423454103] and parameters: {'n_estimators': 60, 'max_depth': 7, 'learning_rate': 0.14892785989469903, 'subsample': 0.7714151258328641, 'colsample_bytree': 0.7103768387750435, 'min_child_weight': 29, 'gamma': 0.23388864857892663, 'lambda': 0.6445960489631807, 'alpha': 2.3780913087737323, 'grow_policy': 'lossguide'}.
[I 2026-07-20 13:14:04,276] Trial 19 finished with values: [0.8834329438560072, 0.0067752785103592835] and parameters: {'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.15970240429475122, 'subsample': 0.7466910667211563, 'colsample_bytree': 0.7937817361728454, 'min_child_weight': 27, 'gamma': 0.12087585888241603, 'lambda': 1.6593615461706548, 'alpha': 2.2687563516094977, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:17:56,717] Trial 20 finished with values: [0.8686474611414365, 0.0015471789619250441] and parameters: {'n_estimators': 120, 'max_depth': 6, 'learning_rate': 0.20077257514431168, 'subsample': 0.701025503579369, 'colsample_bytree': 0.6697150691379062, 'min_child_weight': 27, 'gamma': 0.12539659887915697, 'lambda': 1.0407186618270636, 'alpha': 2.1247947674292633, 'grow_policy': 'lossguide'}.
[I 2026-07-20 13:22:40,702] Trial 21 finished with values: [0.8662045724895092, 0.0013721433685168316] and parameters: {'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.12480839090389298, 'subsample': 0.7736146558929672, 'colsample_bytree': 0.7134414404101095, 'min_child_weight': 25, 'gamma': 0.10513815295817866, 'lambda': 0.6348350763552386, 'alpha': 1.7601577476523513, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:28:05,523] Trial 22 finished with values: [0.8785765877904715, 0.004356519407952719] and parameters: {'n_estimators': 160, 'max_depth': 8, 'learning_rate': 0.152630127781361, 'subsample': 0.7698152090722529, 'colsample_bytree': 0.7294247757628312, 'min_child_weight': 27, 'gamma': 0.12941058925680787, 'lambda': 1.571964929142153, 'alpha': 1.7459653283178835, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:30:18,899] Trial 23 finished with values: [0.8687096224824954, 0.0024542831403327357] and parameters: {'n_estimators': 60, 'max_depth': 9, 'learning_rate': 0.10057877894923942, 'subsample': 0.7945217741556576, 'colsample_bytree': 0.7314452694936187, 'min_child_weight': 23, 'gamma': 0.18360898143866397, 'lambda': 2.2474434663673484, 'alpha': 1.9423543946202424, 'grow_policy': 'lossguide'}.
[I 2026-07-20 13:33:28,154] Trial 24 finished with values: [0.8792956838546677, 0.005219907564265447] and parameters: {'n_estimators': 90, 'max_depth': 9, 'learning_rate': 0.2092898029126333, 'subsample': 0.7787117903083655, 'colsample_bytree': 0.7563422163567607, 'min_child_weight': 30, 'gamma': 0.09578227847696585, 'lambda': 0.654812381804835, 'alpha': 2.39630577250692, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:35:55,448] Trial 25 finished with values: [0.871124855556712, 0.002325494993504629] and parameters: {'n_estimators': 70, 'max_depth': 8, 'learning_rate': 0.15979053290448758, 'subsample': 0.7506430703245613, 'colsample_bytree': 0.7901621024597468, 'min_child_weight': 21, 'gamma': 0.18979651543383663, 'lambda': 0.6461923292532971, 'alpha': 2.165405487055289, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:37:17,125] Trial 26 finished with values: [0.8474109875641289, 0.0005827525300502901] and parameters: {'n_estimators': 40, 'max_depth': 6, 'learning_rate': 0.14098981173551808, 'subsample': 0.7217893410096708, 'colsample_bytree': 0.6589796229397449, 'min_child_weight': 19, 'gamma': 0.20609714222376865, 'lambda': 0.8659166292534356, 'alpha': 2.3043452997002905, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:39:46,612] Trial 27 finished with values: [0.8575478648814034, 0.0004936718478241841] and parameters: {'n_estimators': 80, 'max_depth': 5, 'learning_rate': 0.16451895161360786, 'subsample': 0.7332044228062881, 'colsample_bytree': 0.6780608055776406, 'min_child_weight': 22, 'gamma': 0.17278991125571092, 'lambda': 1.0787372027459443, 'alpha': 1.7309244749419372, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:44:50,408] Trial 28 finished with values: [0.8754649469137338, 0.0031282543308539966] and parameters: {'n_estimators': 150, 'max_depth': 7, 'learning_rate': 0.1806380839503223, 'subsample': 0.7455613377995333, 'colsample_bytree': 0.7590633307676199, 'min_child_weight': 25, 'gamma': 0.1760695567216374, 'lambda': 1.8512310910616807, 'alpha': 2.2230479457095425, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:50:02,181] Trial 29 finished with values: [0.8750892862802964, 0.0035385654197208185] and parameters: {'n_estimators': 90, 'max_depth': 8, 'learning_rate': 0.19976108058717026, 'subsample': 0.7554407370066306, 'colsample_bytree': 0.7610982549242868, 'min_child_weight': 27, 'gamma': 0.0955793410801355, 'lambda': 1.0037680727797824, 'alpha': 2.0659569055755758, 'grow_policy': 'lossguide'}.
[I 2026-07-20 13:54:31,027] Trial 30 finished with values: [0.8664715579901836, 0.0016983015595483987] and parameters: {'n_estimators': 80, 'max_depth': 7, 'learning_rate': 0.15023025591899256, 'subsample': 0.7730830867289684, 'colsample_bytree': 0.6883653871155956, 'min_child_weight': 22, 'gamma': 0.10354230478121366, 'lambda': 0.8538288042626612, 'alpha': 1.7260536352102394, 'grow_policy': 'depthwise'}.
[I 2026-07-20 13:56:50,125] Trial 31 finished with values: [0.8549690130414239, 0.000780511971513631] and parameters: {'n_estimators': 40, 'max_depth': 7, 'learning_rate': 0.10135875264239777, 'subsample': 0.7319467491728183, 'colsample_bytree': 0.7189198077281183, 'min_child_weight': 19, 'gamma': 0.2158631458695134, 'lambda': 0.5263865241218442, 'alpha': 2.3292282070093084, 'grow_policy': 'depthwise'}.
[I 2026-07-20 14:04:43,158] Trial 32 finished with values: [0.8584968623295601, 0.000758821588867642] and parameters: {'n_estimators': 120, 'max_depth': 5, 'learning_rate': 0.12072178992534971, 'subsample': 0.7826466079244997, 'colsample_bytree': 0.7076499131670229, 'min_child_weight': 22, 'gamma': 0.08910426375681559, 'lambda': 0.5606573928118633, 'alpha': 2.299184431522355, 'grow_policy': 'lossguide'}.
[I 2026-07-20 14:11:53,566] Trial 33 finished with values: [0.872084795180655, 0.00255117810850376] and parameters: {'n_estimators': 90, 'max_depth': 8, 'learning_rate': 0.1515362269722268, 'subsample': 0.8052207839511845, 'colsample_bytree': 0.6530698508277052, 'min_child_weight': 20, 'gamma': 0.20882804833150923, 'lambda': 1.3501273511844503, 'alpha': 2.015434026754539, 'grow_policy': 'depthwise'}.
[I 2026-07-20 14:17:55,021] Trial 34 finished with values: [0.8709450371081255, 0.002447910127595354] and parameters: {'n_estimators': 70, 'max_depth': 8, 'learning_rate': 0.16133070259481144, 'subsample': 0.7421308510798522, 'colsample_bytree': 0.7197347428426435, 'min_child_weight': 23, 'gamma': 0.1309933394654475, 'lambda': 1.9792723039190154, 'alpha': 1.9498706579393406, 'grow_policy': 'lossguide'}.
[I 2026-07-20 14:30:03,363] Trial 35 finished with values: [0.8743019355521824, 0.0034899755298807068] and parameters: {'n_estimators': 100, 'max_depth': 9, 'learning_rate': 0.12240510916141589, 'subsample': 0.7542577555449756, 'colsample_bytree': 0.6702787101950628, 'min_child_weight': 30, 'gamma': 0.21994633592922117, 'lambda': 0.5321347130333249, 'alpha': 2.241034817360939, 'grow_policy': 'lossguide'}.
[I 2026-07-20 14:34:10,409] Trial 36 finished with values: [0.8566520935551434, 0.0021016578201110024] and parameters: {'n_estimators': 40, 'max_depth': 9, 'learning_rate': 0.10688040090027331, 'subsample': 0.8010763506725593, 'colsample_bytree': 0.6961930571717189, 'min_child_weight': 20, 'gamma': 0.13914899059564487, 'lambda': 1.7414916635483486, 'alpha': 2.2018376274118943, 'grow_policy': 'depthwise'}.
[I 2026-07-20 14:37:43,329] Trial 37 finished with values: [0.8453822025315546, 0.00033211546194691357] and parameters: {'n_estimators': 50, 'max_depth': 5, 'learning_rate': 0.10520329882637908, 'subsample': 0.7649532340563672, 'colsample_bytree': 0.7783288114821567, 'min_child_weight': 27, 'gamma': 0.18520037091731034, 'lambda': 1.290553674841062, 'alpha': 2.135863324804945, 'grow_policy': 'lossguide'}.
[I 2026-07-20 14:47:37,118] Trial 38 finished with values: [0.8813881473441961, 0.005876251543262922] and parameters: {'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.12604718388748842, 'subsample': 0.7827558256740507, 'colsample_bytree': 0.7474995157055111, 'min_child_weight': 27, 'gamma': 0.08540202392826651, 'lambda': 1.277942874960329, 'alpha': 2.007779102278057, 'grow_policy': 'depthwise'}.
[I 2026-07-20 14:52:25,439] Trial 39 finished with values: [0.8696991962182125, 0.0019193922027263] and parameters: {'n_estimators': 110, 'max_depth': 7, 'learning_rate': 0.1503640791951517, 'subsample': 0.7383005785060149, 'colsample_bytree': 0.6884754671407783, 'min_child_weight': 25, 'gamma': 0.24163591400953244, 'lambda': 1.99359790254274, 'alpha': 2.339842975921788, 'grow_policy': 'depthwise'}.
[I 2026-07-20 14:57:37,577] Trial 40 finished with values: [0.8717850472321546, 0.002067986608889472] and parameters: {'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.2024442053216974, 'subsample': 0.797899811128652, 'colsample_bytree': 0.7574343875588201, 'min_child_weight': 28, 'gamma': 0.1723339219825506, 'lambda': 1.4063006268344824, 'alpha': 1.919431512919829, 'grow_policy': 'lossguide'}.
[I 2026-07-20 14:59:46,270] Trial 41 finished with values: [0.8663960786264319, 0.0015636510219282141] and parameters: {'n_estimators': 60, 'max_depth': 7, 'learning_rate': 0.20674159491581967, 'subsample': 0.7648040628983022, 'colsample_bytree': 0.6681701638842323, 'min_child_weight': 24, 'gamma': 0.1896187419901159, 'lambda': 0.7125449264541478, 'alpha': 1.7603088945526015, 'grow_policy': 'lossguide'}.
[I 2026-07-20 15:03:12,652] Trial 42 finished with values: [0.8691884198378974, 0.002132243589181715] and parameters: {'n_estimators': 60, 'max_depth': 8, 'learning_rate': 0.15287248605030296, 'subsample': 0.7347657112280203, 'colsample_bytree': 0.7214259199146742, 'min_child_weight': 19, 'gamma': 0.2394488172846816, 'lambda': 0.4215994146836738, 'alpha': 2.2037219860328783, 'grow_policy': 'depthwise'}.
[I 2026-07-20 15:08:10,656] Trial 43 finished with values: [0.8642144814973223, 0.0010572905260816778] and parameters: {'n_estimators': 120, 'max_depth': 6, 'learning_rate': 0.12628100055483876, 'subsample': 0.7991003676607775, 'colsample_bytree': 0.6954522150884979, 'min_child_weight': 26, 'gamma': 0.17856637248747256, 'lambda': 1.9762468195241647, 'alpha': 2.1248803718479308, 'grow_policy': 'lossguide'}.
[I 2026-07-20 15:10:28,364] Trial 44 finished with values: [0.8656753077033816, 0.0011472435639431565] and parameters: {'n_estimators': 50, 'max_depth': 7, 'learning_rate': 0.20182450226911455, 'subsample': 0.7335165540478751, 'colsample_bytree': 0.7786298684739271, 'min_child_weight': 30, 'gamma': 0.1908150079449507, 'lambda': 1.3913403551603378, 'alpha': 2.0352930958989797, 'grow_policy': 'lossguide'}.
[I 2026-07-20 15:18:17,525] Trial 45 finished with values: [0.878100208217564, 0.004364660471507098] and parameters: {'n_estimators': 170, 'max_depth': 8, 'learning_rate': 0.1515457039371502, 'subsample': 0.7752092782919505, 'colsample_bytree': 0.6782344292149766, 'min_child_weight': 26, 'gamma': 0.1557227791181092, 'lambda': 0.40150781784787, 'alpha': 1.7737563262159122, 'grow_policy': 'lossguide'}.
[I 2026-07-20 15:26:50,029] Trial 46 finished with values: [0.8821692884857001, 0.005990697420999958] and parameters: {'n_estimators': 150, 'max_depth': 9, 'learning_rate': 0.16445320537030725, 'subsample': 0.774988993735442, 'colsample_bytree': 0.799117334750487, 'min_child_weight': 29, 'gamma': 0.22567439936233968, 'lambda': 0.8339835422426167, 'alpha': 1.914700346600149, 'grow_policy': 'lossguide'}.
[I 2026-07-20 15:33:26,646] Trial 47 finished with values: [0.8713017113098802, 0.002547795969981981] and parameters: {'n_estimators': 120, 'max_depth': 8, 'learning_rate': 0.1040293534007856, 'subsample': 0.7134811006852361, 'colsample_bytree': 0.6667627311510176, 'min_child_weight': 18, 'gamma': 0.13692996423037673, 'lambda': 0.7718931085007197, 'alpha': 1.9693900614898272, 'grow_policy': 'lossguide'}.
[I 2026-07-20 15:36:12,307] Trial 48 finished with values: [0.8619001001674066, 0.0008207121004212281] and parameters: {'n_estimators': 60, 'max_depth': 6, 'learning_rate': 0.1874440770165145, 'subsample': 0.727853643590527, 'colsample_bytree': 0.7858689623907305, 'min_child_weight': 19, 'gamma': 0.14647402442616153, 'lambda': 0.8579780297455134, 'alpha': 1.7300702109287736, 'grow_policy': 'depthwise'}.

In [12]:
best_trials = study.best_trials
i=0

for t in best_trials:
    print(f"{i} val_f1={t.values[0]:.4f}, gap={t.values[1]:.4f}, params={t.params}")
    i+=1

0 val_f1=0.8726, gap=0.0025, params={'n_estimators': 120, 'max_depth': 7, 'learning_rate': 0.16516724609566746, 'subsample': 0.7907493768205527, 'colsample_bytree': 0.7184858951766596, 'min_child_weight': 18, 'gamma': 0.08561689041099817, 'lambda': 1.2794555368058267, 'alpha': 1.7911104661273747, 'grow_policy': 'lossguide'}
1 val_f1=0.8778, gap=0.0041, params={'n_estimators': 160, 'max_depth': 8, 'learning_rate': 0.14044812840025747, 'subsample': 0.7922564975932839, 'colsample_bytree': 0.7909041685848435, 'min_child_weight': 25, 'gamma': 0.23288975582432148, 'lambda': 0.6348280940525617, 'alpha': 1.8473957052567, 'grow_policy': 'depthwise'}
2 val_f1=0.8651, gap=0.0011, params={'n_estimators': 180, 'max_depth': 5, 'learning_rate': 0.15536859475993905, 'subsample': 0.7037615151398394, 'colsample_bytree': 0.6797861959236203, 'min_child_weight': 30, 'gamma': 0.2410429639101309, 'lambda': 1.9215735885968859, 'alpha': 2.1751975697584385, 'grow_policy': 'depthwise'}
3 val_f1=0.8705, gap=0.0018, params={'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.1884524315979021, 'subsample': 0.7196957569859089, 'colsample_bytree': 0.7061000280257759, 'min_child_weight': 18, 'gamma': 0.11307327540956218, 'lambda': 1.3518861928866692, 'alpha': 2.2678694533608614, 'grow_policy': 'depthwise'}
4 val_f1=0.8723, gap=0.0023, params={'n_estimators': 130, 'max_depth': 7, 'learning_rate': 0.149916803987659, 'subsample': 0.819422853145077, 'colsample_bytree': 0.7466049085093802, 'min_child_weight': 21, 'gamma': 0.2253288689297977, 'lambda': 2.25275966065407, 'alpha': 2.3292859872578546, 'grow_policy': 'lossguide'}
5 val_f1=0.8762, gap=0.0038, params={'n_estimators': 120, 'max_depth': 8, 'learning_rate': 0.15836051068953624, 'subsample': 0.8110502423548335, 'colsample_bytree': 0.7237527786962634, 'min_child_weight': 23, 'gamma': 0.13450300657746567, 'lambda': 1.1212941155002818, 'alpha': 1.745060498748975, 'grow_policy': 'depthwise'}
6 val_f1=0.8674, gap=0.0013, params={'n_estimators': 180, 'max_depth': 6, 'learning_rate': 0.11571619022374996, 'subsample': 0.7659765727395559, 'colsample_bytree': 0.6915443995003668, 'min_child_weight': 24, 'gamma': 0.13471768015207275, 'lambda': 0.8268564102915608, 'alpha': 1.9796393282034779, 'grow_policy': 'lossguide'}
7 val_f1=0.8723, gap=0.0023, params={'n_estimators': 180, 'max_depth': 7, 'learning_rate': 0.10637642952538812, 'subsample': 0.7321080383419165, 'colsample_bytree': 0.7452036441124257, 'min_child_weight': 23, 'gamma': 0.1678863984381845, 'lambda': 1.0591063715214335, 'alpha': 2.1445819045238403, 'grow_policy': 'lossguide'}
8 val_f1=0.8834, gap=0.0068, params={'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.15970240429475122, 'subsample': 0.7466910667211563, 'colsample_bytree': 0.7937817361728454, 'min_child_weight': 27, 'gamma': 0.12087585888241603, 'lambda': 1.6593615461706548, 'alpha': 2.2687563516094977, 'grow_policy': 'depthwise'}
9 val_f1=0.8686, gap=0.0015, params={'n_estimators': 120, 'max_depth': 6, 'learning_rate': 0.20077257514431168, 'subsample': 0.701025503579369, 'colsample_bytree': 0.6697150691379062, 'min_child_weight': 27, 'gamma': 0.12539659887915697, 'lambda': 1.0407186618270636, 'alpha': 2.1247947674292633, 'grow_policy': 'lossguide'}
10 val_f1=0.8786, gap=0.0044, params={'n_estimators': 160, 'max_depth': 8, 'learning_rate': 0.152630127781361, 'subsample': 0.7698152090722529, 'colsample_bytree': 0.7294247757628312, 'min_child_weight': 27, 'gamma': 0.12941058925680787, 'lambda': 1.571964929142153, 'alpha': 1.7459653283178835, 'grow_policy': 'depthwise'}
11 val_f1=0.8793, gap=0.0052, params={'n_estimators': 90, 'max_depth': 9, 'learning_rate': 0.2092898029126333, 'subsample': 0.7787117903083655, 'colsample_bytree': 0.7563422163567607, 'min_child_weight': 30, 'gamma': 0.09578227847696585, 'lambda': 0.654812381804835, 'alpha': 2.39630577250692, 'grow_policy': 'depthwise'}
12 val_f1=0.8575, gap=0.0005, params={'n_estimators': 80, 'max_depth': 5, 'learning_rate': 0.16451895161360786, 'subsample': 0.7332044228062881, 'colsample_bytree': 0.6780608055776406, 'min_child_weight': 22, 'gamma': 0.17278991125571092, 'lambda': 1.0787372027459443, 'alpha': 1.7309244749419372, 'grow_policy': 'depthwise'}
13 val_f1=0.8755, gap=0.0031, params={'n_estimators': 150, 'max_depth': 7, 'learning_rate': 0.1806380839503223, 'subsample': 0.7455613377995333, 'colsample_bytree': 0.7590633307676199, 'min_child_weight': 25, 'gamma': 0.1760695567216374, 'lambda': 1.8512310910616807, 'alpha': 2.2230479457095425, 'grow_policy': 'depthwise'}
14 val_f1=0.8585, gap=0.0008, params={'n_estimators': 120, 'max_depth': 5, 'learning_rate': 0.12072178992534971, 'subsample': 0.7826466079244997, 'colsample_bytree': 0.7076499131670229, 'min_child_weight': 22, 'gamma': 0.08910426375681559, 'lambda': 0.5606573928118633, 'alpha': 2.299184431522355, 'grow_policy': 'lossguide'}
15 val_f1=0.8454, gap=0.0003, params={'n_estimators': 50, 'max_depth': 5, 'learning_rate': 0.10520329882637908, 'subsample': 0.7649532340563672, 'colsample_bytree': 0.7783288114821567, 'min_child_weight': 27, 'gamma': 0.18520037091731034, 'lambda': 1.290553674841062, 'alpha': 2.135863324804945, 'grow_policy': 'lossguide'}
16 val_f1=0.8814, gap=0.0059, params={'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.12604718388748842, 'subsample': 0.7827558256740507, 'colsample_bytree': 0.7474995157055111, 'min_child_weight': 27, 'gamma': 0.08540202392826651, 'lambda': 1.277942874960329, 'alpha': 2.007779102278057, 'grow_policy': 'depthwise'}
17 val_f1=0.8718, gap=0.0021, params={'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.2024442053216974, 'subsample': 0.797899811128652, 'colsample_bytree': 0.7574343875588201, 'min_child_weight': 28, 'gamma': 0.1723339219825506, 'lambda': 1.4063006268344824, 'alpha': 1.919431512919829, 'grow_policy': 'lossguide'}
18 val_f1=0.8642, gap=0.0011, params={'n_estimators': 120, 'max_depth': 6, 'learning_rate': 0.12628100055483876, 'subsample': 0.7991003676607775, 'colsample_bytree': 0.6954522150884979, 'min_child_weight': 26, 'gamma': 0.17856637248747256, 'lambda': 1.9762468195241647, 'alpha': 2.1248803718479308, 'grow_policy': 'lossguide'}
19 val_f1=0.8657, gap=0.0011, params={'n_estimators': 50, 'max_depth': 7, 'learning_rate': 0.20182450226911455, 'subsample': 0.7335165540478751, 'colsample_bytree': 0.7786298684739271, 'min_child_weight': 30, 'gamma': 0.1908150079449507, 'lambda': 1.3913403551603378, 'alpha': 2.0352930958989797, 'grow_policy': 'lossguide'}
20 val_f1=0.8822, gap=0.0060, params={'n_estimators': 150, 'max_depth': 9, 'learning_rate': 0.16445320537030725, 'subsample': 0.774988993735442, 'colsample_bytree': 0.799117334750487, 'min_child_weight': 29, 'gamma': 0.22567439936233968, 'lambda': 0.8339835422426167, 'alpha': 1.914700346600149, 'grow_policy': 'lossguide'}
21 val_f1=0.8619, gap=0.0008, params={'n_estimators': 60, 'max_depth': 6, 'learning_rate': 0.1874440770165145, 'subsample': 0.727853643590527, 'colsample_bytree': 0.7858689623907305, 'min_child_weight': 19, 'gamma': 0.14647402442616153, 'lambda': 0.8579780297455134, 'alpha': 1.7300702109287736, 'grow_policy': 'depthwise'}
22 val_f1=0.8706, gap=0.0018, params={'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.1884524315979021, 'subsample': 0.7196957569859089, 'colsample_bytree': 0.7061000280257759, 'min_child_weight': 18, 'gamma': 0.2153454521172395, 'lambda': 1.3518861928866692, 'alpha': 2.2678694533608614, 'grow_policy': 'depthwise'}
23 val_f1=0.8744, gap=0.0027, params={'n_estimators': 150, 'max_depth': 7, 'learning_rate': 0.16133070259481144, 'subsample': 0.7455613377995333, 'colsample_bytree': 0.7590633307676199, 'min_child_weight': 25, 'gamma': 0.1760695567216374, 'lambda': 1.9792723039190154, 'alpha': 1.951519770260508, 'grow_policy': 'lossguide'}
24 val_f1=0.8800, gap=0.0054, params={'n_estimators': 120, 'max_depth': 9, 'learning_rate': 0.15836051068953624, 'subsample': 0.8110502423548335, 'colsample_bytree': 0.7237527786962634, 'min_child_weight': 23, 'gamma': 0.13450300657746567, 'lambda': 1.0591063715214335, 'alpha': 1.745060498748975, 'grow_policy': 'depthwise'}
25 val_f1=0.8307, gap=0.0003, params={'n_estimators': 40, 'max_depth': 5, 'learning_rate': 0.10520329882637908, 'subsample': 0.7649532340563672, 'colsample_bytree': 0.6961930571717189, 'min_child_weight': 28, 'gamma': 0.13914899059564487, 'lambda': 1.7482711224530976, 'alpha': 2.135863324804945, 'grow_policy': 'depthwise'}

In [14]:
params=best_trials[15].params
params

{'n_estimators': 50,
 'max_depth': 5,
 'learning_rate': 0.10520329882637908,
 'subsample': 0.7649532340563672,
 'colsample_bytree': 0.7783288114821567,
 'min_child_weight': 27,
 'gamma': 0.18520037091731034,
 'lambda': 1.290553674841062,
 'alpha': 2.135863324804945,
 'grow_policy': 'lossguide'}

In [16]:
model = xgb.XGBClassifier(
        objective="multi:softprob",
        num_class=3,
        **params,
        tree_method="hist",
        random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)
y_pred1 = model.predict(
    X_train
)

y_pred = model.predict(
    X_test
)
macro_f1_train = f1_score(
    y_train,
    y_pred1,
    average="macro"
)

macro_f1_test = f1_score(
    y_test,
    y_pred,
    average="macro"
)
gap=macro_f1_train-macro_f1_test
print(f" Gap: {gap} Train Macro F1 : {macro_f1_train}  Test Macro F1 : {macro_f1_test}")

 Gap: 0.02743037226727496 Train Macro F1 : 0.8460511151826982  Test Macro F1 : 0.8186207429154232

In [17]:
import joblib

# Save the model
joblib.dump(model, 'xgb_model_GOM.pkl')

['xgb_model_GOM.pkl']

In [13]:
i=0
for t in best_trials:
    params=t.params
    lgb_model = xgb.XGBClassifier(
        objective="multi:softprob",
        num_class=3,
        **params,
        tree_method="hist",
        random_state=42,
        n_jobs=-1
    )

    lgb_model.fit(X_train, y_train)
    y_pred1 = lgb_model.predict(
        X_train
    )

    y_pred = lgb_model.predict(
        X_test
    )
    macro_f1_train = f1_score(
        y_train,
        y_pred1,
        average="macro"
    )

    macro_f1_test = f1_score(
        y_test,
        y_pred,
        average="macro"
    )
    gap=macro_f1_train-macro_f1_test
    print(f"{i} Gap: {gap} Train Macro F1 : {macro_f1_train}  Test Macro F1 : {macro_f1_test}")
    i+=1

0 Gap: 0.04205238343561035 Train Macro F1 : 0.8750081516084123  Test Macro F1 : 0.8329557681728019
1 Gap: 0.04789928065604088 Train Macro F1 : 0.8819468224359693  Test Macro F1 : 0.8340475417799285
2 Gap: 0.03560986535960087 Train Macro F1 : 0.866124474467886  Test Macro F1 : 0.8305146091082851
3 Gap: 0.038905394861400655 Train Macro F1 : 0.8721517428776909  Test Macro F1 : 0.8332463480162903
4 Gap: 0.04056496335841564 Train Macro F1 : 0.874460186343022  Test Macro F1 : 0.8338952229846064
5 Gap: 0.04480499862188192 Train Macro F1 : 0.8793237694140982  Test Macro F1 : 0.8345187707922163
6 Gap: 0.037235050765720756 Train Macro F1 : 0.8686041599721918  Test Macro F1 : 0.831369109206471
7 Gap: 0.04049971322899859 Train Macro F1 : 0.8740928564380953  Test Macro F1 : 0.8335931432090967
8 Gap: 0.058089556903123896 Train Macro F1 : 0.8899237888178183  Test Macro F1 : 0.8318342319146944
9 Gap: 0.03845899202784553 Train Macro F1 : 0.8704054784630588  Test Macro F1 : 0.8319464864352133
10 Gap: 0.048697250208518894 Train Macro F1 : 0.88260996671674  Test Macro F1 : 0.8339127165082211
11 Gap: 0.05093118699044652 Train Macro F1 : 0.8839360558727546  Test Macro F1 : 0.8330048688823081
12 Gap: 0.032744698512944814 Train Macro F1 : 0.8580376417739565  Test Macro F1 : 0.8252929432610117
13 Gap: 0.04422695526317022 Train Macro F1 : 0.8785037718349978  Test Macro F1 : 0.8342768165718276
14 Gap: 0.03305398445493013 Train Macro F1 : 0.8591165440585734  Test Macro F1 : 0.8260625596036433
15 Gap: 0.02743037226727496 Train Macro F1 : 0.8460511151826982  Test Macro F1 : 0.8186207429154232
16 Gap: 0.05436154748236888 Train Macro F1 : 0.8872191413171414  Test Macro F1 : 0.8328575938347725
17 Gap: 0.040919293772903376 Train Macro F1 : 0.8737761560762619  Test Macro F1 : 0.8328568623033585
18 Gap: 0.034683270023071144 Train Macro F1 : 0.8650968204301726  Test Macro F1 : 0.8304135504071014
19 Gap: 0.03638408521656811 Train Macro F1 : 0.86659394100267  Test Macro F1 : 0.8302098557861018
20 Gap: 0.05553749819166043 Train Macro F1 : 0.8883121466763612  Test Macro F1 : 0.8327746484847007
21 Gap: 0.03382344523439662 Train Macro F1 : 0.8625199458354386  Test Macro F1 : 0.8286965006010419
22 Gap: 0.039244466291921576 Train Macro F1 : 0.8719164730461632  Test Macro F1 : 0.8326720067542416
23 Gap: 0.04363602152160506 Train Macro F1 : 0.8771799268393935  Test Macro F1 : 0.8335439053177884
24 Gap: 0.051882610663856354 Train Macro F1 : 0.8850813780296766  Test Macro F1 : 0.8331987673658202
25 Gap: 0.02867123421217066 Train Macro F1 : 0.8307619368004944  Test Macro F1 : 0.8020907025883237

In [2]:
import re

# Paste your full best_trials output here (all lines, as printed)
log_text = """
0 val_f1=0.8762, gap=0.0044, params={'n_estimators': 100, 'max_depth': 10, 'learning_rate': 0.10944709489657091, 'subsample': 0.7317589604995012, 'colsample_bytree': 0.6953290771341716, 'min_child_weight': 30, 'gamma': 0.11387934964586463, 'lambda': 1.0549159239745896, 'alpha': 2.3238756182352653, 'grow_policy': 'lossguide'}
1 val_f1=0.8229, gap=0.0001, params={'n_estimators': 40, 'max_depth': 4, 'learning_rate': 0.11571025679159974, 'subsample': 0.8093042317648745, 'colsample_bytree': 0.7137796330429824, 'min_child_weight': 19, 'gamma': 0.06710552538885642, 'lambda': 1.0497518541996316, 'alpha': 2.3577904235627254, 'grow_policy': 'lossguide'}
2 val_f1=0.8791, gap=0.0049, params={'n_estimators': 150, 'max_depth': 8, 'learning_rate': 0.19951730034429815, 'subsample': 0.8153599430710333, 'colsample_bytree': 0.6637596467644058, 'min_child_weight': 30, 'gamma': 0.07668815448155591, 'lambda': 1.354161833159287, 'alpha': 2.161861867520875, 'grow_policy': 'depthwise'}
3 val_f1=0.8442, gap=0.0002, params={'n_estimators': 170, 'max_depth': 3, 'learning_rate': 0.11020927771886237, 'subsample': 0.7463897677486803, 'colsample_bytree': 0.6851800417789057, 'min_child_weight': 25, 'gamma': 0.20011385667234774, 'lambda': 0.9786677476354191, 'alpha': 2.477017163520082, 'grow_policy': 'lossguide'}
4 val_f1=0.8699, gap=0.0024, params={'n_estimators': 50, 'max_depth': 9, 'learning_rate': 0.13315616116707724, 'subsample': 0.7769848625826535, 'colsample_bytree': 0.7191176265720222, 'min_child_weight': 21, 'gamma': 0.14413392225983668, 'lambda': 2.2250365475502463, 'alpha': 2.3660049667675533, 'grow_policy': 'lossguide'}
5 val_f1=0.8919, gap=0.0164, params={'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.23058151531363136, 'subsample': 0.7065884308315366, 'colsample_bytree': 0.7768362240149912, 'min_child_weight': 25, 'gamma': 0.08358642799951045, 'lambda': 1.645467116437388, 'alpha': 2.2473019769861433, 'grow_policy': 'lossguide'}
6 val_f1=0.8569, gap=0.0005, params={'n_estimators': 160, 'max_depth': 4, 'learning_rate': 0.12045942038422806, 'subsample': 0.7167060585840063, 'colsample_bytree': 0.7906639393105257, 'min_child_weight': 21, 'gamma': 0.05741168609428335, 'lambda': 0.8437252135984831, 'alpha': 2.0966838301719943, 'grow_policy': 'lossguide'}
7 val_f1=0.8683, gap=0.0016, params={'n_estimators': 110, 'max_depth': 7, 'learning_rate': 0.12681834341496523, 'subsample': 0.7983176118838361, 'colsample_bytree': 0.6667188264418532, 'min_child_weight': 28, 'gamma': 0.226545400219929, 'lambda': 0.9493625065932157, 'alpha': 2.1581003973796196, 'grow_policy': 'lossguide'}
8 val_f1=0.8805, gap=0.0058, params={'n_estimators': 180, 'max_depth': 8, 'learning_rate': 0.18875251030281376, 'subsample': 0.7616511421803682, 'colsample_bytree': 0.7086357151625736, 'min_child_weight': 18, 'gamma': 0.07069723855505121, 'lambda': 0.7495944655229668, 'alpha': 2.3503658242522247, 'grow_policy': 'lossguide'}
9 val_f1=0.8755, gap=0.0033, params={'n_estimators': 140, 'max_depth': 7, 'learning_rate': 0.1919612183384838, 'subsample': 0.729443379320247, 'colsample_bytree': 0.7716040252146499, 'min_child_weight': 19, 'gamma': 0.11970646881789365, 'lambda': 0.4921155405678625, 'alpha': 1.7681970041454256, 'grow_policy': 'depthwise'}
10 val_f1=0.8825, gap=0.0066, params={'n_estimators': 200, 'max_depth': 9, 'learning_rate': 0.12265184576472421, 'subsample': 0.8252593884668175, 'colsample_bytree': 0.816588666106996, 'min_child_weight': 21, 'gamma': 0.11683458824067286, 'lambda': 0.629800092334488, 'alpha': 2.3184901734364347, 'grow_policy': 'depthwise'}
11 val_f1=0.8897, gap=0.0128, params={'n_estimators': 180, 'max_depth': 10, 'learning_rate': 0.22711416599737455, 'subsample': 0.7151551830136728, 'colsample_bytree': 0.8014104022716946, 'min_child_weight': 21, 'gamma': 0.14189286921056404, 'lambda': 1.0317780123124702, 'alpha': 2.149407651894446, 'grow_policy': 'depthwise'}
12 val_f1=0.8799, gap=0.0055, params={'n_estimators': 100, 'max_depth': 9, 'learning_rate': 0.20570893291292117, 'subsample': 0.8012349342310094, 'colsample_bytree': 0.8238108906510386, 'min_child_weight': 27, 'gamma': 0.22634627424816425, 'lambda': 1.6914520412510292, 'alpha': 2.3216086954665194, 'grow_policy': 'lossguide'}
13 val_f1=0.8510, gap=0.0003, params={'n_estimators': 130, 'max_depth': 3, 'learning_rate': 0.20257969756813482, 'subsample': 0.7199887402884849, 'colsample_bytree': 0.7278807399942958, 'min_child_weight': 18, 'gamma': 0.06093384356901913, 'lambda': 0.5475813918007015, 'alpha': 2.0826063197693667, 'grow_policy': 'lossguide'}
14 val_f1=0.8910, gap=0.0143, params={'n_estimators': 160, 'max_depth': 13, 'learning_rate': 0.15339484469299375, 'subsample': 0.7544755281964334, 'colsample_bytree': 0.8232719210676371, 'min_child_weight': 23, 'gamma': 0.3965895105648431, 'lambda': 2.2504881618094714, 'alpha': 2.326459971799494, 'grow_policy': 'lossguide'}
15 val_f1=0.8611, gap=0.0007, params={'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.14665598716607936, 'subsample': 0.7041616956257574, 'colsample_bytree': 0.8007085456788328, 'min_child_weight': 25, 'gamma': 0.07833113435533068, 'lambda': 0.4127296129319316, 'alpha': 2.1999696011638976, 'grow_policy': 'lossguide'}
16 val_f1=0.8502, gap=0.0003, params={'n_estimators': 110, 'max_depth': 3, 'learning_rate': 0.22731384282105221, 'subsample': 0.8305319204398793, 'colsample_bytree': 0.8320237657476159, 'min_child_weight': 19, 'gamma': 0.11905222284687504, 'lambda': 2.1731458966759907, 'alpha': 2.77880481722537, 'grow_policy': 'lossguide'}
17 val_f1=0.8950, gap=0.0227, params={'n_estimators': 180, 'max_depth': 14, 'learning_rate': 0.20117839890784578, 'subsample': 0.7818795536534398, 'colsample_bytree': 0.8487569418008967, 'min_child_weight': 27, 'gamma': 0.15766752470485199, 'lambda': 1.3520249934018735, 'alpha': 1.997677705715474, 'grow_policy': 'lossguide'}
18 val_f1=0.8576, gap=0.0006, params={'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.10364766048363648, 'subsample': 0.7809749647192663, 'colsample_bytree': 0.7908309290014222, 'min_child_weight': 30, 'gamma': 0.05287293229210929, 'lambda': 1.3814465698011986, 'alpha': 1.9791262458941516, 'grow_policy': 'lossguide'}
19 val_f1=0.8867, gap=0.0102, params={'n_estimators': 190, 'max_depth': 10, 'learning_rate': 0.18412580232521003, 'subsample': 0.8154561572651473, 'colsample_bytree': 0.6959134810191328, 'min_child_weight': 25, 'gamma': 0.14057402278902642, 'lambda': 0.6133168477196687, 'alpha': 2.7828429276405124, 'grow_policy': 'lossguide'}
20 val_f1=0.8642, gap=0.0015, params={'n_estimators': 90, 'max_depth': 7, 'learning_rate': 0.10939814502545417, 'subsample': 0.7711759130909477, 'colsample_bytree': 0.685405040150334, 'min_child_weight': 22, 'gamma': 0.16638958084244027, 'lambda': 0.8450269956315326, 'alpha': 2.3827941819596896, 'grow_policy': 'depthwise'}
21 val_f1=0.8832, gap=0.0091, params={'n_estimators': 40, 'max_depth': 13, 'learning_rate': 0.23389011437644536, 'subsample': 0.7387879475259895, 'colsample_bytree': 0.8391494659269236, 'min_child_weight': 25, 'gamma': 0.33190150746287034, 'lambda': 0.7084635752357078, 'alpha': 2.1049431206241453, 'grow_policy': 'lossguide'}
22 val_f1=0.8650, gap=0.0016, params={'n_estimators': 70, 'max_depth': 7, 'learning_rate': 0.15437206471266035, 'subsample': 0.7611226379026037, 'colsample_bytree': 0.6783016379944227, 'min_child_weight': 28, 'gamma': 0.10234733040856327, 'lambda': 0.5006541024694537, 'alpha': 2.3089851035723514, 'grow_policy': 'lossguide'}
23 val_f1=0.8901, gap=0.0136, params={'n_estimators': 170, 'max_depth': 12, 'learning_rate': 0.1337711569216201, 'subsample': 0.8003895366355729, 'colsample_bytree': 0.7562873506879672, 'min_child_weight': 22, 'gamma': 0.22143332980386596, 'lambda': 1.252124957764437, 'alpha': 1.7229309104252324, 'grow_policy': 'depthwise'}
24 val_f1=0.8811, gap=0.0060, params={'n_estimators': 170, 'max_depth': 9, 'learning_rate': 0.12876176667516329, 'subsample': 0.7938732306938991, 'colsample_bytree': 0.7741859773197596, 'min_child_weight': 24, 'gamma': 0.08022037505313662, 'lambda': 1.2001995093362452, 'alpha': 1.8929748712904222, 'grow_policy': 'depthwise'}
25 val_f1=0.8849, gap=0.0102, params={'n_estimators': 80, 'max_depth': 13, 'learning_rate': 0.11341025064273932, 'subsample': 0.8392670788821844, 'colsample_bytree': 0.7690051358944665, 'min_child_weight': 18, 'gamma': 0.28130984804064707, 'lambda': 2.345692539166496, 'alpha': 1.8201161520759477, 'grow_policy': 'lossguide'}
26 val_f1=0.8882, gap=0.0111, params={'n_estimators': 140, 'max_depth': 11, 'learning_rate': 0.17721090893209832, 'subsample': 0.8155179062550316, 'colsample_bytree': 0.7192516974525307, 'min_child_weight': 21, 'gamma': 0.26457821813619475, 'lambda': 1.4993574218413432, 'alpha': 2.6207755881420063, 'grow_policy': 'lossguide'}
""".strip()  # <-- replace with the FULL pasted block (all 27 lines)

pattern = r"(\d+) val_f1=([\d.]+), gap=([\d.]+), params=(\{.*?\})"
matches = re.findall(pattern, log_text)

trials = []
for num, val_f1, gap, params_str in matches:
    trials.append({
        "trial": int(num),
        "cv_val_f1": float(val_f1),
        "cv_gap": float(gap),
        "params": eval(params_str)
    })

print(f"Parsed {len(trials)} trials")

Parsed 27 trials

In [8]:
i=0
for t in trials:
    params=t["params"]
    lgb_model = xgb.XGBClassifier(
    objective='multiclass',
    num_class=3,
    **params,
    random_state=42
    )

    lgb_model.fit(X_train, y_train)
    y_pred1 = lgb_model.predict(
        X_train
    )

    y_pred = lgb_model.predict(
        X_test
    )
    macro_f1_train = f1_score(
        y_train,
        y_pred1,
        average="macro"
    )

    macro_f1_test = f1_score(
        y_test,
        y_pred,
        average="macro"
    )
    gap=macro_f1_train-macro_f1_test
    print(f"{i} Gap: {gap} Train Macro F1 : {macro_f1_train}  Test Macro F1 : {macro_f1_test}")
    i+=1

0 Gap: 0.049790522795544856 Train Macro F1 : 0.8804754627533914  Test Macro F1 : 0.8306849399578465
1 Gap: 0.028309487248564413 Train Macro F1 : 0.8232318723586296  Test Macro F1 : 0.7949223851100652
2 Gap: 0.05096859354536443 Train Macro F1 : 0.8836802603828086  Test Macro F1 : 0.8327116668374441
3 Gap: 0.028384462955062695 Train Macro F1 : 0.8446843739601805  Test Macro F1 : 0.8162999110051178
4 Gap: 0.0409147406745608 Train Macro F1 : 0.8723711495952241  Test Macro F1 : 0.8314564089206633
5 Gap: 0.08225389726848142 Train Macro F1 : 0.9083968139781522  Test Macro F1 : 0.8261429167096708
6 Gap: 0.03174109053454843 Train Macro F1 : 0.8573241589664011  Test Macro F1 : 0.8255830684318527
7 Gap: 0.038265792521352315 Train Macro F1 : 0.8694535509754232  Test Macro F1 : 0.8311877584540709
8 Gap: 0.05293950247704515 Train Macro F1 : 0.8857499945757134  Test Macro F1 : 0.8328104920986682
9 Gap: 0.04407606125170316 Train Macro F1 : 0.878344017781654  Test Macro F1 : 0.8342679565299509
10 Gap: 0.05695600025890346 Train Macro F1 : 0.8889813914428322  Test Macro F1 : 0.8320253911839287
11 Gap: 0.07207900448047244 Train Macro F1 : 0.9020829364747353  Test Macro F1 : 0.8300039319942628
12 Gap: 0.05213215880514044 Train Macro F1 : 0.8856488368184013  Test Macro F1 : 0.8335166780132609
13 Gap: 0.030347177260854452 Train Macro F1 : 0.8513736769037067  Test Macro F1 : 0.8210264996428522
14 Gap: 0.0778410947887549 Train Macro F1 : 0.9055950540667738  Test Macro F1 : 0.8277539592780189
15 Gap: 0.03397801401835654 Train Macro F1 : 0.8618538544573582  Test Macro F1 : 0.8278758404390016
16 Gap: 0.03072803436909166 Train Macro F1 : 0.8503101710032853  Test Macro F1 : 0.8195821366341937
17 Gap: 0.09283607060823418 Train Macro F1 : 0.9177692807566499  Test Macro F1 : 0.8249332101484157
18 Gap: 0.03165007922274976 Train Macro F1 : 0.8581524663090203  Test Macro F1 : 0.8265023870862706
19 Gap: 0.06788535466408852 Train Macro F1 : 0.8968453362050778  Test Macro F1 : 0.8289599815409893
20 Gap: 0.03570469266201126 Train Macro F1 : 0.8652731493126719  Test Macro F1 : 0.8295684566506606
21 Gap: 0.06112701137421972 Train Macro F1 : 0.8923913165551175  Test Macro F1 : 0.8312643051808978
22 Gap: 0.0375442698058549 Train Macro F1 : 0.8666136639480877  Test Macro F1 : 0.8290693941422328
23 Gap: 0.07407766002854033 Train Macro F1 : 0.9033771334437812  Test Macro F1 : 0.8292994734152409
24 Gap: 0.05310772872674008 Train Macro F1 : 0.8868722266196359  Test Macro F1 : 0.8337644978928959
25 Gap: 0.0649054526943309 Train Macro F1 : 0.8952969180684547  Test Macro F1 : 0.8303914653741238
26 Gap: 0.06898135285259643 Train Macro F1 : 0.8994456865001664  Test Macro F1 : 0.83046433364757

In [ ]:
i=0
for t in best_trials:
    params=t.params
    lgb_model = xgb.XGBClassifier(
    objective='multiclass',
    num_class=3,
    **params,
    random_state=42
    )

    lgb_model.fit(X_train, y_train)
    y_pred1 = lgb_model.predict(
        X_train
    )

    y_pred = lgb_model.predict(
        X_test
    )
    macro_f1_train = f1_score(
        y_train,
        y_pred1,
        average="macro"
    )

    macro_f1_test = f1_score(
        y_test,
        y_pred,
        average="macro"
    )
    gap=macro_f1_train-macro_f1_test
    print(f"{i} Gap: {gap} Train Macro F1 : {macro_f1_train}  Test Macro F1 : {macro_f1_test}")
    i+=1

0 Gap: 0.05262558775782644 Train Macro F1 : 0.8854324203205097  Test Macro F1 : 0.8328068325626833
1 Gap: 0.08342420267633133 Train Macro F1 : 0.9102737889448292  Test Macro F1 : 0.8268495862684979
2 Gap: 0.043893066218946175 Train Macro F1 : 0.8768974398411326  Test Macro F1 : 0.8330043736221864
3 Gap: 0.06406841682260256 Train Macro F1 : 0.8941944821218916  Test Macro F1 : 0.830126065299289
4 Gap: 0.1011935326511898 Train Macro F1 : 0.9243613951883529  Test Macro F1 : 0.8231678625371631
5 Gap: 0.08024611828751071 Train Macro F1 : 0.9075758901069192  Test Macro F1 : 0.8273297718194085
6 Gap: 0.0836242694375735 Train Macro F1 : 0.9108267340578012  Test Macro F1 : 0.8272024646202277
7 Gap: 0.05985071864147817 Train Macro F1 : 0.8912609902156965  Test Macro F1 : 0.8314102715742183
8 Gap: 0.06132709361964883 Train Macro F1 : 0.8930262857474299  Test Macro F1 : 0.8316991921277811
9 Gap: 0.07602507871997699 Train Macro F1 : 0.9042740592060169  Test Macro F1 : 0.8282489804860399
10 Gap: 0.040142889045924335 Train Macro F1 : 0.8708897852962951  Test Macro F1 : 0.8307468962503708
11 Gap: 0.0822118713420602 Train Macro F1 : 0.9093393327774062  Test Macro F1 : 0.827127461435346
12 Gap: 0.09090866257294239 Train Macro F1 : 0.915605160141879  Test Macro F1 : 0.8246964975689366
13 Gap: 0.053455087918885535 Train Macro F1 : 0.8864361400686823  Test Macro F1 : 0.8329810521497968
14 Gap: 0.07052717129896802 Train Macro F1 : 0.8993149977236182  Test Macro F1 : 0.8287878264246502
15 Gap: 0.02867595771302689 Train Macro F1 : 0.8427430720134019  Test Macro F1 : 0.814067114300375
16 Gap: 0.028379418234830034 Train Macro F1 : 0.8425219293626597  Test Macro F1 : 0.8141425111278296
17 Gap: 0.04733086309339685 Train Macro F1 : 0.8810719557470263  Test Macro F1 : 0.8337410926536295
18 Gap: 0.08331931597039721 Train Macro F1 : 0.9099877036545262  Test Macro F1 : 0.826668387684129
19 Gap: 0.03636866215132051 Train Macro F1 : 0.8677928611892961  Test Macro F1 : 0.8314241990379756
20 Gap: 0.04572121279089114 Train Macro F1 : 0.8786436639309435  Test Macro F1 : 0.8329224511400524
21 Gap: 0.07600389080413583 Train Macro F1 : 0.9043746488308387  Test Macro F1 : 0.8283707580267029
22 Gap: 0.03778010333138593 Train Macro F1 : 0.8699121770409001  Test Macro F1 : 0.8321320737095141
23 Gap: 0.034711190710031925 Train Macro F1 : 0.864092336549748  Test Macro F1 : 0.8293811458397161
24 Gap: 0.06754951908331086 Train Macro F1 : 0.897554585756334  Test Macro F1 : 0.8300050666730231
25 Gap: 0.07441310391761446 Train Macro F1 : 0.9025084371224384  Test Macro F1 : 0.828095333204824
26 Gap: 0.09617756885880191 Train Macro F1 : 0.919687198680046  Test Macro F1 : 0.8235096298212441
27 Gap: 0.03206706738462195 Train Macro F1 : 0.8576405443261912  Test Macro F1 : 0.8255734769415692

In [46]:
params=best_trials[16].params
params

{'n_estimators': 140,
 'max_depth': 3,
 'learning_rate': 0.10881987858257748,
 'subsample': 0.8446526339839784,
 'colsample_bytree': 0.8003642023896022,
 'min_child_weight': 20,
 'gamma': 0.2573469603906708,
 'lambda': 2.302483337281246,
 'alpha': 2.462096139775924,
 'grow_policy': 'depthwise'}